window.providerSheetsFallbackData = {
  "providers": [
    {
      "id": "manual-1777301718029",
      "source": "google-sheets-approved",
      "name": "Albert Einstein Israelite Hospital",
      "type": "Hospital/Clinic",
      "agreement": "Agreement pending",
      "main_country": "Brazil",
      "country": "Brazil",
      "city": "São Paulo",
      "region": "SP",
      "lat": -23.6000507,
      "lon": -46.7152458,
      "address": "Av. Albert Einstein, 627/701 - Morumbi, São Paulo - SP, 05652-900, Brazil",
      "network_manager": "International Department",
      "ops_phone": "(55) 11 2151 1301",
      "ops_email": "international@einstein.br / contact@einstein.br",
      "website": "https://www.einstein.br/estrutura/unidades/morumbi",
      "comments": "Serves Sao Paulo (capital city of the State of Sao Paulo)."
    },
    {
      "id": "manual-1781698836775",
      "source": "google-sheets-approved",
      "name": "Renova Hospital",
      "type": "Hospital/Clinic",
      "agreement": "Agreement signed",
      "main_country": "Nepal",
      "country": "Nepal",
      "city": "Pokhara",
      "lat": 28.2141417,
      "lon": 83.95774999999999,
      "address": "Lakeside - 06, Hallan Chowk, Pokhara 33700",
      "ops_phone": "+977 9813377736",
      "ops_email": "ips@renovahospital.com / admin@renovahospital.com / info@renovahospital.com"
    },
    {
      "id": "manual-1781699198876",
      "source": "google-sheets-approved",
      "name": "CIWEC Hospital",
      "type": "Hospital/Clinic",
      "agreement": "Agreement signed",
      "main_country": "Nepal",
      "country": "Nepal",
      "city": "Pokhara",
      "lat": 28.2095831,
      "lon": 83.9855674,
      "address": "14th Street, Mansarovar Path, Lakeside, Pokhara-6",
      "ops_phone": "+977 61 453082 / 457053 / Mobile +977 9856013130",
      "ops_email": "pkrbookings@ciwec-clinic.com / pkradministrator@ciwec-clinic.com",
      "website": "ciwechospital.com"
    },
    {
      "id": "manual-1781901530993",
      "source": "google-sheets-approved",
      "name": "Dentist Dr. Holger Maßen",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Germany",
      "country": "Germany",
      "city": "41747 Viersen",
      "lat": 51.2585483,
      "lon": 6.3848502,
      "address": "Remigiusstraße 1A, 41747 Viersen",
      "ops_phone": "0049 (0)2162-20756",
      "ops_email": "dr.massen@gmail.com",
      "website": "https://www.zahnarzt-in-viersen.de/",
      "comments": "Accepts our GOP / no contract / Lisa June 2026"
    },
    {
      "id": "manual-1782170110913",
      "source": "google-sheets-approved",
      "name": "Air Medic",
      "type": "Air Ambulance",
      "agreement": "Agreement signed",
      "main_country": "Canada",
      "country": "Canada",
      "lat": 45.5189662,
      "lon": -73.411671,
      "address": "Saint-Hubert Airport , 4980 Airport Road, Saint-Hubert, QC J3Y 8Y9",
      "ops_phone": "+1-877-999-3322 / +1 239-672-3664 (cell) / +1 450-766-0770 ext. 680",
      "ops_email": "repatriation@airmedic.net",
      "website": "https://www.airmedic.net/"
    },
    {
      "id": "manual-1782909874557",
      "source": "google-sheets-approved",
      "name": "Hospital Parque Levant",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Palma de Mallorca",
      "country": "Palma de Mallorca",
      "city": "Porto Cristo",
      "lat": 39.5450731,
      "lon": 3.3292905,
      "address": "Carrer de l'escamarla 6, 07680 Porto Christo",
      "ops_phone": "+34971822400",
      "ops_email": "URGENCIAS.LLV@HOSPITALESPARQUE.es, gop.llv@hospitalesparque.es",
      "comments": "Accepting our GOP - please send request to: URGENCIAS.LLV@HOSPITALESPARQUE.es, gop.llv@hospitalesparque.es"
    },
    {
      "id": "manual-1782910642865",
      "source": "google-sheets-approved",
      "name": "ZUGER KANTONSSPITAL",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Switzerland",
      "country": "Switzerland",
      "city": "Baar",
      "lat": 47.1940506,
      "lon": 8.5179008,
      "address": "Landhausstrasse 11, 6340 Baar, Schweiz",
      "network_manager": "Henseler Monika (Accounting)",
      "ops_phone": "+41 41 399 11 11",
      "ops_email": "kogu@zgks.ch, Versicherungen@zgks.ch, monika.henseler@zgks.ch",
      "comments": "EHIC will be accepted / and accepting our GOP. Invoices will take at least 4-6 weeks / OPEN 24/7"
    },
    {
      "id": "manual-1782910760949",
      "source": "google-sheets-approved",
      "name": "Luzerner Kantonsspital",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Switzerland",
      "country": "Switzerland",
      "city": "Luzern",
      "lat": 47.0584861,
      "lon": 8.2971831,
      "address": "Kantonsspital 37, 6004 Luzern, Schweiz",
      "ops_email": "daniela.waldispuehl@luks.ch, berichte.luks@luks.ch, stationaer.luks@luks.ch",
      "comments": "accepting EHIC as well / and accept our GOP / invoices between 4-6 weeks"
    },
    {
      "id": "manual-1782911165868",
      "source": "google-sheets-approved",
      "name": "Kantonsspital Uri",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Switzerland",
      "country": "Switzerland",
      "city": "Altdorf",
      "region": "Uri",
      "lat": 46.8825161,
      "lon": 8.6373976,
      "address": "Spitalstrasse 1, 6460 Altdorf, Schweiz",
      "ops_phone": "+41 41 875 51 51",
      "ops_email": "empfang@ksuri.ch, petra.marty@ksuri.ch,  sekretariat.assistenzaerzte@ksuri.ch",
      "website": "www.ksuri.ch",
      "comments": "Accept our GOP / and EHIC / open 24/7"
    },
    {
      "id": "manual-1782911334773",
      "source": "google-sheets-approved",
      "name": "Schweizerisches Rotes Kreuz Kantonalverband Uri",
      "type": "Ground Ambulance",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Switzerland",
      "country": "Switzerland",
      "city": "Altdorf",
      "region": "Uri",
      "lat": 46.8723418,
      "lon": 8.6329513,
      "address": "Rynächtstrasse 13 CH-6460 Altdorf",
      "ops_phone": "041 874 30 75",
      "ops_email": "info@srk-uri.ch, buchhaltung@srk-uri.ch",
      "website": "https://www.srk-uri.ch/kontakt",
      "comments": "arrange ground ambulances in the area (and to the airport if needed)"
    },
    {
      "id": "manual-1782911540062",
      "source": "google-sheets-approved",
      "name": "Kantonsspital Graubünden",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Switzerland",
      "country": "Switzerland",
      "city": "Chur",
      "lat": 46.8639071,
      "lon": 9.539766199999999,
      "address": "Loestrasse 170, 7000 Chur, Schweiz",
      "ops_phone": "+41 81 256 61 11",
      "ops_email": "patientenabrechnung@ksgr.ch, patientenaufnahme@ksgr.ch",
      "website": "https://www.ksgr.ch/kontakt",
      "comments": "Accept our GOP / open 24/7 - accept EHIC as well"
    },
    {
      "id": "manual-1782911820175",
      "source": "google-sheets-approved",
      "name": "Universitätsspital Basel",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Switzerland",
      "country": "Switzerland",
      "city": "Basel",
      "region": "Petersgraben 4/Spitalstrasse 21  4031 Basel",
      "lat": 47.5595986,
      "lon": 7.5885761,
      "ops_phone": "+41 61 265 25 25",
      "ops_email": "fakturierung@usb.ch, scmeddok@usb.ch",
      "website": "https://www.unispital-basel.ch/kontakt",
      "comments": "Accept our GOP / EHIC accepted? unknown! // very slow and bad communication! very complicated"
    },
    {
      "id": "manual-1782911988158",
      "source": "google-sheets-approved",
      "name": "Augenzentrum LuzernNord",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Switzerland",
      "country": "Switzerland",
      "city": "Luzern",
      "lat": 47.0700923,
      "lon": 8.2805131,
      "address": "Gerliswilstrasse 15, 6020 Emmenbrücke",
      "ops_phone": "041 260 15 20",
      "ops_email": "augenemmen@hin.ch",
      "comments": "accept our GOP"
    },
    {
      "id": "manual-1782912158979",
      "source": "google-sheets-approved",
      "name": "Dr. med. Robert Rouhi, Facharzt für Innere Medizin FMH",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Switzerland",
      "country": "Switzerland",
      "region": "St. Moritz",
      "lat": 46.4977987,
      "lon": 9.8381588,
      "address": "Via Traunter Plazzas 5 7500 St. Moritz",
      "ops_phone": "+41 81 837 30 30",
      "ops_email": "info@rouhi-med.ch",
      "website": "https://www.rouhi-med.ch/kontakt/",
      "comments": "accept our GOP / also doing house-call visits in the area / OPENING HOURS Mo. - Fr.: 08.00 - 12.00 und 14.00 - 18.00. Do.: 08.00 - 12.00, (only open in the afternoon in winter seasons)"
    },
    {
      "id": "manual-1782912492163",
      "source": "google-sheets-approved",
      "name": "Dr. med. Robert Rouhi - House Call Visit",
      "type": "House Calls",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Switzerland",
      "country": "Switzerland",
      "city": "St. Moritz",
      "region": "Engadin",
      "lat": 46.4977987,
      "lon": 9.8381588,
      "address": "Via Traunter plazzas 5, 7500 St. Moritz",
      "ops_phone": "+41 81 837 30 30",
      "ops_email": "info@rouhi-med.ch",
      "website": "https://www.rouhi-med.ch/leistungen/",
      "comments": "Doing House Call Visits in this area and accepting our GOP"
    },
    {
      "id": "manual-1782912769107",
      "source": "google-sheets-approved",
      "name": "Universitätsspital Zürich (USZ)",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Switzerland",
      "country": "Switzerland",
      "city": "Zürich",
      "lat": 47.3764458,
      "lon": 8.5502091,
      "address": "Rämistrasse 100, 8091 Zürich, Schweiz",
      "ops_phone": "+41 44 255 11 11",
      "ops_email": "fin.amb@usz.ch, international@usz.ch",
      "website": "https://www.usz.ch/en/international-patients/",
      "comments": "accept our GOP / open 24/7 - very slow in communication"
    },
    {
      "id": "manual-1783321216051",
      "source": "google-sheets-approved",
      "name": "UniMed",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Turkey",
      "country": "Turkey",
      "city": "Bodrum",
      "lat": 37.0336833,
      "lon": 27.4013056,
      "address": "Albay M. Halit Talayer Sokak No: 2/A Gümbet / Bodrum",
      "ops_phone": "+90 252 319 57 57",
      "ops_email": "info@unimed.com.tr",
      "comments": "they accept our GOP / and granted us a discount in the end of the case - very helpful and nice. speaking EN & DE in the administration / available on whatsapp too; +90 542 423 46 93 (WhatsApp)"
    },
    {
      "id": "manual-1783419697747",
      "source": "google-sheets-approved",
      "name": "Zahnarztpraxis Hörnö AG",
      "type": "Dental",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Liechtenstein",
      "country": "Liechtenstein",
      "city": "Mauren",
      "lat": 47.218084,
      "lon": 9.543216,
      "address": "Weiherring 16 9493 Mauren FL",
      "ops_phone": "00423 371 11 21",
      "ops_email": "info@hoernoe.li",
      "comments": "They accept our GOP"
    },
    {
      "id": "manual-1783429477690",
      "source": "google-sheets-approved",
      "name": "Gemeinschaftspraxis Silvia und Matthias Merkl (GP) - Internist, Hausarzt",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Germany",
      "country": "Germany",
      "city": "Wunsiedel",
      "lat": 50.0406321,
      "lon": 12.00404,
      "address": "Bibersbacher Strasse 2, 95632 Wunsiedel",
      "ops_phone": "+49 (0) 9232 99 60 60",
      "ops_email": "tagesklinik.wunsiedel@web.de",
      "website": "http://www.hausarzt-wunsiedel.de/",
      "comments": "GOP accepted - including Home visits in urgent cases"
    },
    {
      "id": "manual-1783429770071",
      "source": "google-sheets-approved",
      "name": "Praxis für Orthopädie und Unfallchirurgie Rastatt",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Germany",
      "country": "Germany",
      "city": "Rastatt",
      "lat": 48.8676329,
      "lon": 8.2070324,
      "address": "Richard-Wagner-Ring 28 76437 Rastatt",
      "ops_phone": "004972 22 - 64 46",
      "ops_email": "info@orthopaedie-ra.de",
      "website": "www.orthopädie-rastatt.de",
      "comments": "Gemeinschaftspraxis Dres. med. Jörg Meiforth und Jens Wagner\nFachärzte für Orthopädie und Unfallchirurgie\n\nAccepting our GOP BUT (!) invoice will be sent per post ! no invoice per mail possible"
    },
    {
      "id": "manual-1783430139212",
      "source": "google-sheets-approved",
      "name": "Dermatologie am Sittardsberg (Dermatologist)",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Germany",
      "country": "Germany",
      "city": "Duisburg",
      "lat": 51.3751598,
      "lon": 6.7607591,
      "address": "Altenbrucher Damm 15 47249 Duisburg",
      "ops_email": "info@derma-duisburg.de",
      "website": "https://www.derma-duisburg.de/index.php",
      "comments": "Accepting our GOP"
    },
    {
      "id": "manual-1783767833284",
      "source": "google-sheets-approved",
      "name": "HNO-Gemeinschaftspraxis Düsseldorf",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Germany",
      "country": "Germany",
      "city": "Düsseldorf",
      "lat": 51.2364976,
      "lon": 6.8014128,
      "address": "Herderstr. 59 40237 Düsseldorf-Zoo",
      "ops_phone": "+49 (0) 211 673540",
      "ops_email": "praxis@hno-team.de",
      "website": "https://www.hno-team.de/kontakt",
      "comments": "Accepted our GOP in case DUPU - but sending invoices only per post- and very late (2-3 weeks)"
    },
    {
      "id": "manual-1783770293254",
      "source": "google-sheets-approved",
      "name": "All Dent - Zahnzentrum Berlin",
      "type": "Dental",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Germany",
      "country": "Germany",
      "city": "Berlin",
      "lat": 52.5195301,
      "lon": 13.3884452,
      "address": "Friedrichstr. 94 10117Berlin",
      "ops_phone": "0049 30 587 691 11 0",
      "ops_email": "berlin@alldent.de",
      "comments": "GOP accepted"
    },
    {
      "id": "manual-1783771036716",
      "source": "google-sheets-approved",
      "name": "Praxis für Zahnheilkunde Helene Kraft",
      "type": "Dental",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Germany",
      "country": "Germany",
      "city": "Twistringen",
      "lat": 52.7974833,
      "lon": 8.642261699999999,
      "address": "Bahnhofstraße 31, 27239 Twistringen",
      "network_manager": "Mrs. Bollhorst",
      "ops_phone": "+49 4243 941656",
      "ops_email": "info@zahnarzt-twistringen.de",
      "website": "https://zahnarzt.firmenfreund.de/11644-zahnarztpraxis-helene-kraft",
      "comments": "accepting our GOP - we had already two cases there"
    },
    {
      "id": "manual-1783771210425",
      "source": "google-sheets-approved",
      "name": "Zahnarztpraxis Dr. Holger Maßen",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Germany",
      "country": "Germany",
      "city": "Viersen",
      "lat": 51.2585483,
      "lon": 6.3848502,
      "address": "Remigiusstr. 1a 41747 Viersen",
      "ops_phone": "00492162-20756",
      "ops_email": "dr.massen@gmail.com",
      "website": "https://www.zahnarzt-in-viersen.de/kontakt.html",
      "comments": "accepting our GOP"
    },
    {
      "id": "manual-1783771572291",
      "source": "google-sheets-approved",
      "name": "Klinikum Fichtelgebirge Marktredwitz",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Germany",
      "country": "Germany",
      "city": "Marktredwitz",
      "lat": 50.0016876,
      "lon": 12.0660372,
      "address": "Schillerhain 1, 8 95615 Marktredwitz",
      "ops_phone": "0049 9231 809 - 0",
      "ops_email": "info@klinikum-fichtelgebirge.de",
      "website": "https://www.klinikum-fichtelgebirge.de/de/kontakt/",
      "comments": "send GOP to Mr Scharnagl (Accounting Dept). r.scharnagl@Klinikum-Fichtelgebirge.de"
    },
    {
      "id": "manual-1783771893093",
      "source": "google-sheets-approved",
      "name": "MVZ Zahnzentrum Kudamm GmbH c/o MVZ Dental21 - Schöneberg",
      "type": "Dental",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Germany",
      "country": "Germany",
      "city": "Berlin",
      "lat": 52.5027674,
      "lon": 13.3246568,
      "address": "Kurfürstendamm 33, 10719 Berlin",
      "ops_email": "team@dental21-schoeneberg.de",
      "website": "https://www.dental21-kudamm.de/",
      "comments": "GOP accepted"
    },
    {
      "id": "manual-1783774385892",
      "source": "google-sheets-approved",
      "name": "GP: Hausärztliche Gemeinschaftspraxis",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Germany",
      "country": "Germany",
      "city": "Lahntal - Sterzhausen,",
      "lat": 50.8638811,
      "lon": 8.7085779,
      "address": "Wittgensteiner Straße 41, 35094 Lahntal - Sterzhausen,",
      "ops_phone": "0049 6420 335",
      "ops_email": "praxis@lahntalarzt.de",
      "website": "https://hausaerzte.org/lahntal/dr-med-hans-albrecht-oehler/#google_vignette",
      "comments": "accepted our GOP - Hausarztpraxis Sterzhausen,Wittgensteinerstr.41, 35094 Lahntal"
    },
    {
      "id": "manual-1783774878080",
      "source": "google-sheets-approved",
      "name": "GP: Hausarztpraxis Dr. Juricke",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Germany",
      "country": "Germany",
      "city": "Bremen",
      "lat": 53.048327,
      "lon": 8.8486122,
      "address": "Steinsetzerstraße 11 (im Werder-Karree) 28279 Bremen",
      "ops_email": "info@praxis-juricke.de",
      "website": "https://praxis-juricke.de/",
      "comments": "GOP accepted"
    },
    {
      "id": "manual-1783775073544",
      "source": "google-sheets-approved",
      "name": "St. Bernhard-Hospital Kamp-Lintfort GmbH",
      "type": "Hospital/Clinic",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Germany",
      "country": "Germany",
      "city": "Kamp-Lintfort",
      "lat": 51.492448,
      "lon": 6.515831299999999,
      "address": "Bürgermeister-Schmelzing-Str. 90 47475 Kamp-Lintfort",
      "ops_phone": "00490 28 42  7080",
      "ops_email": "pforte@st-bernhard-hospital.de",
      "website": "https://www.st-bernhard-hospital.de/startseite.html",
      "comments": "Important notes: The patient should proceed to the “Pforte” for registration. After that, she will be directed to the emergency department.\n\nIt is important that she goes to the “Pforte” first to obtain our GOP there, as otherwise the emergency department will not be able to accept it.\n\npforte@st-bernhard-hospital.de & info@st-bernhard-hospital.de\nFAX: 0049 (0) 2842 70 84 44"
    },
    {
      "id": "manual-1783787122854",
      "source": "google-sheets-approved",
      "name": "Dr. Vladimir Stankovic Zahnarzt",
      "type": "Dental",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Germany",
      "country": "Germany",
      "city": "Bad Friedrichshall",
      "lat": 49.2281217,
      "lon": 9.2094453,
      "address": "Rathausplatz 2 – 74177 Bad Friedrichshall",
      "ops_phone": "07136/6085",
      "ops_email": "rezeption@zahnarzt-bad-friedrichshall.de",
      "comments": "GOP accepted"
    },
    {
      "id": "manual-1783793154154",
      "source": "google-sheets-approved",
      "name": "Zahngeyer, Zahnarztpraxis Dr. Geyer",
      "type": "Dental",
      "agreement": "GOP accepted - no DBA",
      "main_country": "Austria",
      "country": "Austria",
      "city": "Vienna",
      "lat": 48.1875402,
      "lon": 16.2831285,
      "address": "Hietzinger Hauptstraße 82-84/1, 1130 Wien",
      "ops_phone": "0043 (01) 877 15 50",
      "ops_email": "dr.geyer@zahngeyer.at",
      "website": "https://zahngeyer.at/kontakt/kontakt",
      "comments": "GOP will be accepted"
    },
    {
      "id": "manual-1784177703530",
      "source": "google-sheets-approved",
      "name": "Clínica Brugal Melosa",
      "type": "Hospital/Clinic",
      "agreement": "Agreement signed",
      "main_country": "Dominican Republic",
      "country": "Dominican Republic",
      "city": "Puerto Plata",
      "lat": 19.799162,
      "lon": -70.6924332,
      "address": "Calle José del Carmen Ariza #15, Puerto Plata 57000, Dominican Republic",
      "ops_phone": "+1 829 755 4940",
      "ops_email": "international@melosa.com.do",
      "comments": "Agreement signed, accepting our GOP - you can reach them on whatsapp too:\n+1 829 755 4940 (24/7, including WhatsApp) // international@melosa.com.do & in CC: heidy.ramos@melosa.com.do"
    }
  ],
  "categories": [
    "House Calls"
  ],
  "changes": [
    {
      "change_action": "edit",
      "change_summary": "Provider name: \"TYROL AIR\" -> \"TYROL AIR AMBULANCE (TAA)\"\nCity: (blank) -> \"6020 Innsbruck\"\nLatitude: \"47.33333\" -> (blank)\nLongitude: \"13.33333\" -> (blank)\nAddress: (blank) -> \"Fürstenweg 180, 6020 Innsbruck\"\nEmail: \"air.ambulance@taa.at\" -> \"taa@taa.at\"\nWebsite: (blank) -> \"https://www.taa.at/flug-ambulanz/\"",
      "target_provider": {
        "name": "TYROL AIR",
        "type": "Air Ambulance",
        "agreement": "Agreement pending",
        "main_country": "AUSTRIA",
        "country": "AUSTRIA",
        "region": "EUROPE",
        "lat": 47.33333,
        "lon": 13.33333,
        "ops_phone": "+43 512 22422100",
        "ops_email": "air.ambulance@taa.at"
      },
      "provider": {
        "id": "manual-1781901726998",
        "source": "google-sheets-approved-edit",
        "name": "TYROL AIR AMBULANCE (TAA)",
        "type": "Air Ambulance",
        "agreement": "Agreement pending",
        "main_country": "AUSTRIA",
        "country": "AUSTRIA",
        "city": "6020 Innsbruck",
        "region": "EUROPE",
        "lat": 47.26056029999999,
        "lon": 11.3783617,
        "address": "Fürstenweg 180, 6020 Innsbruck",
        "ops_phone": "+43 512 22422100",
        "ops_email": "taa@taa.at",
        "website": "https://www.taa.at/flug-ambulanz/"
      },
      "request_notes": "wrong location - they are based in Innsbruck at the airport"
    },
    {
      "change_action": "edit",
      "change_summary": "Phone: \"+44 28 9442 2646 +44 (0) 77 250 58040\" -> \"+44 28 9442 2646+44 (0) 77 250 58040\"\nEmail: \"operations@247aviation.co.uk, gail.barkes@247aviation.co.uk neil.crooks@247aviation.co.uk\" -> \"operations@247aviation.co.uk, gail.barkes@247aviation.co.ukneil.crooks@247aviation.co.uk\"\nNotes: (blank) -> \"Mrs Fiona MULLIGAN (Flight co-ordinator); medical; Mrs Claire GRADY (INVOICING)\"",
      "target_provider": {
        "name": "247 AVIATION LIMITED",
        "type": "Air Ambulance",
        "agreement": "Agreement signed",
        "main_country": "Crumlin",
        "country": "IRELAND",
        "city": "Crumlin",
        "region": "EUROPE",
        "lat": 54.6575,
        "lon": -6.2158,
        "address": "BELFAST INTERNATIONAL AIRPORT, Ballyrobin Rd, BT28 4AB, Crumlin",
        "network_manager": "Gail Barkes RN; Neil CROOKS (Director)",
        "ops_phone": "+44 28 9442 2646\n+44 (0) 77 250 58040",
        "ops_email": "operations@247aviation.co.uk, gail.barkes@247aviation.co.uk\nneil.crooks@247aviation.co.uk",
        "website": "www.247aviation.co.uk"
      },
      "provider": {
        "id": "manual-1782226605172",
        "source": "google-sheets-approved-edit",
        "name": "247 AVIATION LIMITED",
        "type": "Air Ambulance",
        "agreement": "Agreement signed",
        "main_country": "Crumlin",
        "country": "Crumlin",
        "city": "Crumlin",
        "region": "EUROPE",
        "lat": 54.6575,
        "lon": -6.2158,
        "address": "BELFAST INTERNATIONAL AIRPORT, Ballyrobin Rd, BT28 4AB, Crumlin",
        "network_manager": "Gail Barkes RN; Neil CROOKS (Director)",
        "ops_phone": "+44 28 9442 2646+44 (0) 77 250 58040",
        "ops_email": "operations@247aviation.co.uk, gail.barkes@247aviation.co.ukneil.crooks@247aviation.co.uk",
        "website": "www.247aviation.co.uk",
        "comments": "Mrs Fiona MULLIGAN (Flight co-ordinator); medical; Mrs Claire GRADY (INVOICING)"
      }
    },
    {
      "change_action": "edit",
      "change_summary": "No field changes detected; see request notes.",
      "target_provider": {
        "id": "germany-22087-hamburg-marienkrankenhaus-hamburg",
        "source": "germany-hospital-clinic-import-2026-06-19",
        "name": "Marienkrankenhaus Hamburg",
        "type": "Hospital/Clinic",
        "agreement": "Agreement pending",
        "main_country": "Germany",
        "country": "Germany",
        "city": "Hamburg",
        "region": "Germany",
        "lat": 53.559033,
        "lon": 10.0307399,
        "address": "Alfredstrasse 9, 22087 Hamburg, Germany",
        "ops_phone": "040 2546-0",
        "ops_email": "info@marienkrankenhaus.org",
        "website": "https://www.marienkrankenhaus.org",
        "comments": "Specialties: Surgery; Trauma/accident surgery; Gynecology and obstetrics; ENT; Internal medicine; Geriatrics; Neurology; Urology."
      },
      "provider": {
        "id": "germany-22087-hamburg-marienkrankenhaus-hamburg",
        "source": "google-sheets-approved-edit",
        "name": "Marienkrankenhaus Hamburg",
        "type": "Hospital/Clinic",
        "agreement": "Agreement pending",
        "main_country": "Germany",
        "country": "Germany",
        "city": "Hamburg",
        "region": "Germany",
        "lat": 53.559033,
        "lon": 10.0307399,
        "address": "Alfredstrasse 9, 22087 Hamburg, Germany",
        "ops_phone": "040 2546-0",
        "ops_email": "info@marienkrankenhaus.org",
        "website": "https://www.marienkrankenhaus.org",
        "comments": "Specialties: Surgery; Trauma/accident surgery; Gynecology and obstetrics; ENT; Internal medicine; Geriatrics; Neurology; Urology."
      },
      "request_notes": "Central Emergency Department (Zentrale Notaufnahme)\nAngerstraße 16\n22087 Hamburg, Germany\nvia: House 1, Entrance A, Ground Floor (Central Emergency Department)\n\n\n European Health Insurance Card (EHIC) will be accepted.\n\n\nIf PAT has no valid EHIC, the hospital requires an upfront payment of EUR 200 for the initial assessment. Any additional costs will be invoiced to you upon discharge/check-out."
    },
    {
      "change_action": "edit",
      "change_summary": "Category: \"Hospital/Clinic\" -> \"House Calls\"",
      "target_provider": {
        "id": "austria-doc-around-the-town",
        "source": "austria-mymaps-gop-2026",
        "name": "Doc around the Town - Dr. Abdo Fakhreddine",
        "type": "Hospital/Clinic",
        "agreement": "GOP accepted - no DBA",
        "main_country": "Austria",
        "country": "Austria",
        "city": "Vienna",
        "region": "Wien",
        "lat": 48.2084337,
        "lon": 16.3683413,
        "address": "Habsburgergasse 10/11, 1010 Wien, Austria",
        "network_manager": "Dr. Abdo Fakhreddine",
        "ops_phone": "+43 660 7077 684",
        "ops_email": "office@docaroundthetown.com",
        "website": "https://docaroundthetown.com/",
        "comments": "Private doctor - GOP accepted without signed DBA. House-call and hotel-doctor visits only for Vienna and surrounding areas."
      },
      "provider": {
        "id": "austria-doc-around-the-town",
        "source": "google-sheets-approved-edit",
        "name": "Doc around the Town - Dr. Abdo Fakhreddine",
        "type": "House Calls",
        "agreement": "GOP accepted - no DBA",
        "main_country": "Austria",
        "country": "Austria",
        "city": "Vienna",
        "region": "Wien",
        "lat": 48.2084337,
        "lon": 16.3683413,
        "address": "Habsburgergasse 10/11, 1010 Wien, Austria",
        "network_manager": "Dr. Abdo Fakhreddine",
        "ops_phone": "+43 660 7077 684",
        "ops_email": "office@docaroundthetown.com",
        "website": "https://docaroundthetown.com/",
        "comments": "Private doctor - GOP accepted without signed DBA. House-call and hotel-doctor visits only for Vienna and surrounding areas."
      }
    },
    {
      "change_action": "edit",
      "change_summary": "Notes: \"Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled ...\" -> \"Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled ...\"",
      "target_provider": {
        "id": "austria-wien-floridsdorf-kl",
        "source": "austria-hospital-import-2026-06-19",
        "name": "Floridsdorf KL",
        "type": "Hospital/Clinic",
        "agreement": "Agreement pending",
        "main_country": "Austria",
        "country": "Austria",
        "city": "Wien",
        "region": "Wien",
        "lat": 48.270136,
        "lon": 16.404719,
        "address": "Bruenner Strasse 73, 1210 Wien, Austria",
        "ops_phone": "01 277 00 0",
        "website": "https://klinik-floridsdorf.gesundheitsverbund.at",
        "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
      },
      "provider": {
        "id": "austria-wien-floridsdorf-kl",
        "source": "google-sheets-approved-edit",
        "name": "Floridsdorf KL",
        "type": "Hospital/Clinic",
        "agreement": "Agreement pending",
        "main_country": "Austria",
        "country": "Austria",
        "city": "Wien",
        "region": "Wien",
        "lat": 48.270136,
        "lon": 16.404719,
        "address": "Bruenner Strasse 73, 1210 Wien, Austria",
        "ops_phone": "01 277 00 0",
        "website": "https://klinik-floridsdorf.gesundheitsverbund.at",
        "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care.\n\ninvoice will be sent by post - you can request the invoice at: kanzlei-21@ma6.wien.gv.at & kfl.finanzAmbVer@gesundheitsverbund.at (GOP can be accepted)"
      },
      "request_notes": "invoice will be sent by post - you can request the invoice at: kanzlei-21@ma6.wien.gv.at & kfl.finanzAmbVer@gesundheitsverbund.at (GOP can be accepted)"
    },
    {
      "change_action": "edit",
      "change_summary": "Agreement status: \"Agreement signed\" -> \"Agreement pending\"\nPhone: \"+33 2 35 30 14 19 +33 2 35 21 32 32 // +33 6 11 18 00 01\" -> \"+33 2 35 30 14 19+33 2 35 21 32 32 // +33 6 11 18 00 01\"",
      "target_provider": {
        "name": "AMBULANCES DE L´ ESTUAIRE",
        "type": "Ground Ambulance",
        "agreement": "Agreement signed",
        "main_country": "Le Havre",
        "region": "FRANCE",
        "lat": 49.49346,
        "lon": 0.10785,
        "network_manager": "Michael Rouziou",
        "ops_phone": "+33 2 35 30 14 19\n+33 2 35 21 32 32 // +33 6 11 18 00 01",
        "ops_email": "regulation@ambulancesestuaire.com"
      },
      "provider": {
        "id": "manual-1784053253224",
        "source": "google-sheets-approved-edit",
        "name": "AMBULANCES DE L´ ESTUAIRE",
        "type": "Ground Ambulance",
        "agreement": "Agreement pending",
        "main_country": "Le Havre",
        "country": "Le Havre",
        "region": "FRANCE",
        "lat": 49.49346,
        "lon": 0.10785,
        "network_manager": "Michael Rouziou",
        "ops_phone": "+33 2 35 30 14 19+33 2 35 21 32 32 // +33 6 11 18 00 01",
        "ops_email": "regulation@ambulancesestuaire.com"
      }
    },
    {
      "change_action": "edit",
      "change_summary": "Category: \"TPA\" -> \"House Calls\"\nAgreement status: \"AGREEMENT SIGNED\" -> \"Agreement pending\"\nPhone: \"+51 967 011 285 +51 985 324 578\" -> \"+51 967 011 285+51 985 324 578\"",
      "target_provider": {
        "name": "DOCTOR CUSCO",
        "type": "TPA",
        "agreement": "AGREEMENT SIGNED",
        "main_country": "Peru",
        "lat": -10,
        "lon": -76,
        "network_manager": "David Quispe",
        "ops_phone": "+51 967 011 285\n+51 985 324 578",
        "ops_email": "ops.doctorcusco@gmail.com  info@doctorcusco.com"
      },
      "provider": {
        "id": "manual-1784261541137",
        "source": "google-sheets-approved-edit",
        "name": "DOCTOR CUSCO",
        "type": "House Calls",
        "agreement": "Agreement pending",
        "main_country": "Peru",
        "country": "Peru",
        "lat": -10,
        "lon": -76,
        "network_manager": "David Quispe",
        "ops_phone": "+51 967 011 285+51 985 324 578",
        "ops_email": "ops.doctorcusco@gmail.com  info@doctorcusco.com"
      }
    }
  ]
};
