const hospitalClinicProviders = [
  {
    id: "austria-tirol-kliniken-innsbruck",
    source: "austria-mymaps-gop-2026",
    name: "Tirol Kliniken Innsbruck",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Innsbruck",
    region: "Tirol",
    lat: 47.2615435,
    lon: 11.3851307,
    address: "Anichstrasse 35, A-6020 Innsbruck, Austria",
    network_manager: "Hansjoerg Schloegl (billing/GOP contact)",
    ops_phone: "+43 50 504-0",
    ops_email: "hansjoerg.schloegl@tirol-kliniken.at",
    website: "https://www.tirol-kliniken.at/page.cfm?vpath=standorte%2Flandeskrankenhaus-innsbruck",
    comments: "Public hospital - GOP accepted without signed DBA. Test for 2026: no direct contract, no cost estimate available, invoice normally issued after discharge. For inpatient admission email patient name and DOB to hansjoerg.schloegl@tirol-kliniken.at. Outpatient invoices are normally sent to the patient's home address; email the same contact to request invoice if Compass Point Assist covers. Full medical report is available at least 7 days after discharge via same contact. Repatriation must be discussed directly with treating ward doctor.",
  },
  {
    id: "austria-st-vinzenz-zams",
    source: "austria-mymaps-gop-2026",
    name: "St. Vinzenz Hospital Zams",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Zams",
    region: "Tirol",
    lat: 47.1614186,
    lon: 10.5940799,
    address: "Sanatoriumstrasse 43, A-6511 Zams, Austria",
    network_manager: "Patient billing / responsible medical office",
    ops_phone: "+43 5442 600",
    ops_email: "patient@krankenhaus-zams.at; unfall@krankenhaus-zams.at; office@krankenhaus-zams.at",
    website: "https://www.khzams.at/en/",
    comments: "Public hospital - GOP accepted without signed DBA for non-EHIC inpatient admission. For EHIC inpatient admissions, hospital daily allowance must be paid by patient at discharge. Medical reports are available after discharge only; requests must go to the responsible medical office/department, not patient billing. Trauma report contact from MyMaps notes: unfall@krankenhaus-zams.at. Patient billing contact from MyMaps notes: patient@krankenhaus-zams.at. Outpatient treatment may require partial payment on site and is generally pay-and-claim.",
  },
  {
    id: "austria-bkh-kufstein",
    source: "austria-mymaps-gop-2026",
    name: "Bezirkskrankenhaus Kufstein",
    type: "Hospital/Clinic",
    agreement: "GOP accepted case-by-case - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Kufstein",
    region: "Tirol",
    lat: 47.571767,
    lon: 12.1498691,
    address: "Endach 27, A-6330 Kufstein, Austria",
    network_manager: "Hospital administration",
    ops_phone: "+43 5372 6966-0",
    ops_email: "direktion@bkh-kufstein.at",
    website: "https://www.bkh-kufstein.at/de/kontakt.html",
    comments: "Public hospital - no signed direct billing contract. MyMaps notes say GOP/cost guarantee acceptance must be assessed case by case. Hospital requires a patient-signed release of medical information before sharing further details.",
  },
  {
    id: "austria-zellmed-medalp",
    source: "austria-mymaps-gop-2026",
    name: "Zellmed Medalp",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Zell am Ziller",
    region: "Tirol",
    lat: 47.2355047,
    lon: 11.8899151,
    address: "Stocklerfeld 6, 6280 Zell am Ziller, Austria",
    network_manager: "Medalp coordination",
    ops_phone: "+43 5282 4200; emergency +43 699 1611 9988",
    ops_email: "office@zellmed.at; info@medalp.com",
    website: "https://medalp.com/en/location/aerztehaus-zellmed/",
    comments: "GOP accepted without signed DBA. Medalp/Zellmed test phase for winter season 2026: GOP for first visit, EUR 1,000, should be sent before patient transfer to Medalp.",
  },
  {
    id: "austria-allgemeinpraxis-soelden-medalp",
    source: "austria-mymaps-gop-2026",
    name: "Allgemeinpraxis Soelden (Medalp Gruppe)",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Soelden",
    region: "Tirol",
    lat: 46.9697001,
    lon: 11.0096738,
    address: "Gemeindestrasse 1, 6450 Soelden, Austria",
    network_manager: "Medalp coordination",
    ops_phone: "+43 5254 2040; emergency +43 699 1611 9988",
    ops_email: "praxis-soelden@medalp.com; info@medalp.com",
    website: "https://medalp.com/en/location/allgemeinpraxis-soelden/",
    comments: "Private practice - GOP accepted without signed DBA. Medalp test phase for winter season 2026: GOP for first visit, EUR 1,000, should be sent before patient transfer to Medalp.",
  },
  {
    id: "austria-sportclinic-zillertal",
    source: "austria-mymaps-gop-2026",
    name: "Sportclinic Zillertal (Medalp Group)",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Mayrhofen",
    region: "Tirol",
    lat: 47.158721,
    lon: 11.846253,
    address: "Stillupklamm 830, 6290 Mayrhofen, Austria",
    network_manager: "Medalp coordination",
    ops_phone: "+43 5285 78485; emergency +43 699 1611 9988",
    ops_email: "office@sportclinic.at; info@medalp.com",
    website: "https://medalp.com/en/location/sportclinic-zillertal/",
    comments: "Private clinic - GOP accepted without signed DBA. Medalp test phase for winter season 2026: GOP for first visit, EUR 1,000, should be sent before patient transfer to Medalp. Source note dated 17/02/2026.",
  },
  {
    id: "austria-medalp-imst",
    source: "austria-mymaps-gop-2026",
    name: "medalp Imst - Medalp Sportclinic Imst GmbH",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Imst",
    region: "Tirol",
    lat: 47.214087,
    lon: 10.699678,
    address: "Medalp Platz 1, 6460 Imst, Austria",
    network_manager: "Medalp coordination",
    ops_phone: "+43 5418 51100; emergency +43 699 1611 9988",
    ops_email: "info@medalp.com",
    website: "https://medalp.com/en/location/sportclinic-imst/",
    comments: "Private clinic - GOP accepted without signed DBA. Medalp test phase for winter season 2026: GOP for first visit, EUR 1,000, should be sent before patient transfer to Medalp. Source note dated 17/02/2026.",
  },
  {
    id: "austria-medalp-sportclinic-soelden",
    source: "austria-mymaps-gop-2026",
    name: "medalp sportclinic Soelden - Gruppenpraxis fuer Unfallchirurgie Dr. Alois Schranz, Dr. Manfred Lener OG",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Soelden",
    region: "Tirol",
    lat: 46.9588407,
    lon: 11.0091484,
    address: "Dorfstrasse 160, 6450 Soelden, Austria",
    network_manager: "Medalp coordination",
    ops_phone: "+43 5254 30003; emergency +43 699 1611 9988",
    ops_email: "soelden@medalp.com; info@medalp.com",
    website: "https://medalp.com/en/location/sportclinic-soelden/",
    comments: "Private clinic - GOP accepted without signed DBA. Medalp test phase for winter season 2026: GOP for first visit, EUR 1,000, should be sent before patient transfer to Medalp. Source contact note: soelden@medalp.com, 18/02/2026.",
  },
  {
    id: "austria-medserfaus",
    source: "austria-mymaps-gop-2026",
    name: "Medserfaus Praxis - Hausapotheke",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Serfaus",
    region: "Tirol",
    lat: 47.0403035,
    lon: 10.5973277,
    address: "Dorfbahnstrasse 79, 6534 Serfaus, Austria",
    network_manager: "Mrs Koehle (CEO referral contact)",
    ops_phone: "+43 5476 53000; CEO mobile +43 650 6531053",
    ops_email: "info@medserfaus.at",
    website: "https://www.medserfaus.at/med-serfaus/kontakt-lage",
    comments: "Private practice - GOP accepted without signed DBA, but prompt payment is required. Before referral: contact CEO Mrs Koehle on +43 650 6531053, confirm internal handling, and email info@medserfaus.at with patient details. Medical report and invoice are provided after treatment. Serfaus is car-free, but access by car to this medical facility is permitted with parking directly in front.",
  },
  {
    id: "austria-lkh-villach",
    source: "austria-mymaps-gop-2026",
    name: "KABEG Landeskrankenhaus Villach",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Villach",
    region: "Kaernten",
    lat: 46.615932,
    lon: 13.85778,
    address: "Nikolaigasse 43, 9500 Villach, Austria",
    network_manager: "APMV / patient administration",
    ops_phone: "+43 4242 208-0",
    ops_email: "apmv@kabeg.at; lkh.villach@kabeg.at",
    website: "https://www.lkh-villach.at/",
    comments: "Public hospital - GOP accepted without signed DBA. Send GOP to apmv@kabeg.at. Final invoice expected 4-6 weeks after patient discharge. Source note dated 17/02/2026.",
  },
  {
    id: "austria-mrt-kaprun",
    source: "austria-mymaps-gop-2026",
    name: "MRT Kaprun - Kaprun Diagnostik - Facharztpraxen - Priv.-Doz. DDr. Karl Egger",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Kaprun",
    region: "Salzburg",
    lat: 47.2825959,
    lon: 12.7555589,
    address: "Tauern Spa Strasse 16, 5710 Kaprun, Austria",
    network_manager: "Kaprun Diagnostik team",
    ops_phone: "+43 6547 20505",
    ops_email: "info@mrt-kaprun.at",
    website: "https://www.mrt-kaprun.at/",
    comments: "Private diagnostic/specialist practice - GOP accepted without signed DBA. Send medical report and MEDEX requests to info@mrt-kaprun.at.",
  },
  {
    id: "austria-doc-around-the-town",
    source: "austria-mymaps-gop-2026",
    name: "Doc around the Town - Dr. Abdo Fakhreddine",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Vienna",
    region: "Wien",
    lat: 48.2084337,
    lon: 16.3683413,
    address: "Habsburgergasse 10/11, 1010 Wien, Austria",
    network_manager: "Dr. Abdo Fakhreddine",
    ops_phone: "+43 660 7077 684",
    ops_email: "office@docaroundthetown.com",
    website: "https://docaroundthetown.com/",
    comments: "Private doctor - GOP accepted without signed DBA. House-call and hotel-doctor visits only for Vienna and surrounding areas.",
  },
  {
    id: "indonesia-bali-international-hospital",
    source: "network-manager-2026-06-08",
    name: "Bali International Hospital",
    type: "Hospital/Clinic",
    agreement: "Agreement signed",
    main_country: "Indonesia",
    country: "Indonesia",
    city: "Denpasar",
    region: "Bali",
    lat: -8.6790039,
    lon: 115.2590574,
    address: "Jalan Kawasan Ekonomi Khusus Sanur, Lot H1-H2, Desa/Kelurahan Sanur Kaja, Kec. Denpasar Selatan, Kota Denpasar, Provinsi Bali, Kode Pos: 80227",
    network_manager: "Network Manager referral",
    ops_phone: "+62 811-3831-8590; +62 811-3810-1721 (WhatsApp); +62 811-3831-8590 (Mobile)",
    ops_email: "admission@bih.id; insurance@bih.id",
    website: "https://bih.id/",
    comments: "Provider details supplied by Network Manager on 08/06/2026.",
  },
  {
    id: "colombia-traumacentro-medellin",
    source: "network-manager-2026-06-08",
    name: "Traumacentro",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Colombia",
    country: "Colombia",
    city: "Medellin",
    region: "Antioquia",
    lat: 6.2459225,
    lon: -75.5836604,
    address: "Carrera 65 # 42-20, Barrio San Joaquin, Medellin, Antioquia, Colombia",
    network_manager: "Network Manager referral",
    ops_phone: "+57 318 812 1280 (WhatsApp)",
    ops_email: "referencia@clinicatraumacentro.com",
    website: "https://clinicatraumacentro.com/",
    comments: "TraumaCentro SAS / NIT 901094037-3. Provider details supplied by Network Manager on 08/06/2026.",
  },
  // Austria hospital import - 2026-06-19
  {
    "id": "austria-klagenfurt-am-woerthersee-lkh-klagenfurt-kabeg-group",
    "source": "austria-hospital-import-2026-06-19",
    "name": "LKH Klagenfurt - KABEG Group",
    "type": "Hospital/Clinic",
    "agreement": "GOP accepted - no DBA",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Klagenfurt am Woerthersee",
    "region": "Kaernten",
    "lat": 46.6344367,
    "lon": 14.3072132,
    "address": "Feschnigstrasse 11, 9020 Klagenfurt am Woerthersee, Austria",
    "ops_phone": "tel +43 463 538-0",
    "ops_email": "klinikum.klagenfurt@kabeg.at",
    "website": "https://www.klinikum-klagenfurt.at/",
    "comments": "Owner/type: PUBLIC. PUBLIC - but will accept our GOP: klinikum.klagenfurt@kabeg.at EHIC will be accepted too MAIN FOCUS: General healthcare / general medical care"
  },
  {
    "id": "austria-ramsau-im-zillertal-orthopaetdie-zillertal-not-opened-yet-grand-opening-autumn-2026",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Orthopaetdie Zillertal (not opened yet) - GRAND OPENING AUTUMN 2026",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Ramsau im Zillertal",
    "region": "Tirol",
    "lat": 47.2059424,
    "lon": 11.8767625,
    "address": "Ramsau 160, 6284 Ramsau im Zillertal, Austria",
    "ops_phone": "0043 664 61827220 Dr.",
    "ops_email": "Askackov@gmail.com",
    "comments": "Owner/type: PRIVATE. Opening hours: not known - opening hours TBA. PRIVATE - Clinic not opend yet - (opening in Winter Seaoson 2026/27) They will accept our GOP: Askackov@gmail.com (new e-mail Adress will be given once the clinic has been opened) MAIN FOCUS: Accident and sports trauma"
  },
  {
    "id": "austria-ischgl-sportchirurgie-ischgl-dr-schenk",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Sportchirurgie Ischgl Dr. Schenk",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Ischgl",
    "region": "Tirol",
    "lat": 47.0152809,
    "lon": 10.294787,
    "address": "Florianplatz 1c, 6561 Ischgl, Austria",
    "ops_phone": "0 5444 50027",
    "ops_email": "info@sport-chirurgie-ischgl.at",
    "website": "https://www.dr-schenk.at/klinik/sport-chirurgie-ischgl/",
    "comments": "Owner/type: PRIVATE. PRIVATE - PAY & CLAIM ONLY MAIN FOCUS: Accident and sports trauma"
  },
  {
    "id": "austria-telfs-ordination-dr-markus-kopriva-aerztehaus-telfs",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Ordination Dr. Markus Kopriva (Aerztehaus Telfs)",
    "type": "Hospital/Clinic",
    "agreement": "Agreement signed",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Telfs",
    "region": "Tirol",
    "lat": 47.3030928,
    "lon": 11.0685128,
    "address": "Marktplatz 7/2 Telfs, 6410 Telfs, Austria",
    "ops_phone": "0043 5262 65175 / contact Janna: 0043 664 401 88 30",
    "ops_email": "info@ordination-kopriva.at",
    "comments": "Owner/type: PRIVATE. \"PRIVATE: GOP accepted: please send email to info@ordination-kopriva.at & call Janna from the reception immediately to coordinate the appointment (0043 664 401 88 30) Accident & Sports Trauma Center - X-ray and MRI diagnostics available on site, including surgical treatment and trauma surgery. -> contract signed on 08JUN2026\" MAIN FOCUS: Accident and sports trauma"
  },
  {
    "id": "austria-gerlos-unfallpraxis-gerlos",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Unfallpraxis Gerlos",
    "type": "Hospital/Clinic",
    "agreement": "Agreement signed",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Gerlos",
    "region": "Tirol",
    "lat": 47.2256991,
    "lon": 12.0342498,
    "address": "Gerlos 141, 6281 Gerlos, Austria",
    "ops_phone": "05284 94104",
    "ops_email": "info@unfallpraxis-gerlos.at",
    "website": "https://www.unfallpraxis-gerlos.at/",
    "comments": "Owner/type: PRIVATE. Opening hours: MO-SO 09:00-18:00. PRIVATE - contract signed May 2026 They accept our GOP - info@unfallpraxis-gerlos.at Please always call them as they might be very busy in the high season: 0043 (0) 5284 94104 MAIN FOCUS: Accident and sports trauma"
  },
  {
    "id": "austria-innsbruck-unfallpraxis-dr-christian-dallapozza",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Unfallpraxis Dr. Christian Dallapozza",
    "type": "Hospital/Clinic",
    "agreement": "Agreement signed",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Innsbruck",
    "region": "Tirol",
    "lat": 47.2560683,
    "lon": 11.3774184,
    "address": "Innrain 143, 3. Stock, 6020 Innsbruck, Austria",
    "ops_phone": "Tel. +43 (0) 512 9010 3090",
    "ops_email": "info@unfallpraxis-dallapozza.at",
    "website": "https://www.unfallpraxis-dallapozza.at/",
    "comments": "Owner/type: PRIVATE. Opening hours: Montag: 08 - 13 und 16 - 18 Uhr Dienstag: 08 - 12 Uhr Mittwoch nur nach Vereinbarung Donnerstag: 08 - 13 und 16 - 18 Uhr Freitag: 08 - 12 Uhr von 8 - 11 Uhr: Ambulanzbetrieb fuer Frischverletzte Patienten. PRIVATE - contract signed May 2026 They accept our GOP - info@unfallpraxis-dallapozza.at -> Appointment needed! no ER (Private doc) MAIN FOCUS: Accident and sports trauma"
  },
  {
    "id": "austria-hall-in-tirol-hall-in-tirol-lkh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Hall in Tirol LKH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Hall in Tirol",
    "region": "Tirol",
    "lat": 47.2823607,
    "lon": 11.5152023,
    "address": "Milser Strasse 10, 6060 Hall in Tirol, Austria",
    "ops_phone": "05223 508 0",
    "ops_email": "hall.office@tirol-kliniken.at",
    "website": "https://www.tirol-kliniken.at/page.cfm?vpath=standorte/landeskrankenhaus-hall",
    "comments": "Owner/type: PUBLIC. PUBLIC: OUTPATIENT: Emergency treatment only - no pre-arranged appointments possible / no GOP acceptance. Patient must pay all costs upfront. Medical reports (MR) will be handed directly to the patient upon discharge. INPATIENT: Admission possible with GOP. Appointment/admission must be arranged in advance with the relevant department. However, due to limited capacity, the hospital usually cannot accommodate international patients and cases are often referred to Innsbruck or Schwaz instead. MR & MEDEX can be requested after discharge; however, the process is usually complicated and time-consuming. MAIN FOCUS: general hospital & Accident an..."
  },
  {
    "id": "austria-schwaz-schwaz-bkh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Schwaz BKH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement signed",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Schwaz",
    "region": "Tirol",
    "lat": 47.344755,
    "lon": 11.7056621,
    "address": "Swarovskistrasse 1, 6130 Schwaz, Austria",
    "ops_phone": "05242 600 0",
    "ops_email": "aufnahme@kh-schwaz.at / info@kh-schwaz.at",
    "website": "https://www.kh-schwaz.at/",
    "comments": "Owner/type: PUBLIC. PUBLIC - GOP will be accepted. No agreement signed. Please request MR & MEDEX from aufnahme@kh-schwaz.at GOP to aufnahme@kh-schwaz.at MAIN FOCUS: general hospital & Accident and sports trauma"
  },
  {
    "id": "austria-wald-im-pinzgau-unfallpraxis-koenigsleiten-dr-kopriva",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Unfallpraxis Koenigsleiten, Dr. Kopriva",
    "type": "Hospital/Clinic",
    "agreement": "Agreement signed",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Wald im Pinzgau",
    "region": "Salzburg",
    "lat": 47.2463426,
    "lon": 12.1182493,
    "address": "Koenigsleiten 310, 5742 Wald im Pinzgau, Austria",
    "ops_phone": "06564 94144",
    "ops_email": "info@unfallpraxis-koenigsleiten.at",
    "website": "https://www.unfallpraxis-koenigsleiten.at/",
    "comments": "Owner/type: PRIVATE. Opening hours: MO-SO 09:00-18:00. PRIVATE: GOP accepted: please send email to info@unfallpraxis-koenigsleiten.at & call them immediately to coordinate the appointment (no agreement signed but will accept our GOP) - Same owner -> of the Private Center in Telfs (Dr. Markus Kopriva) MAIN FOCUS: Accident and sports trauma"
  },
  {
    "id": "austria-saalfelden-am-steinernen-meer-privatklinik-ritzensee",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Privatklinik Ritzensee",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Saalfelden am Steinernen Meer",
    "region": "Salzburg",
    "lat": 47.4166794,
    "lon": 12.8511682,
    "address": "Schmalenbergham 4, 5760 Saalfelden am Steinernen Meer, Austria",
    "ops_phone": "T: +43 (0) 6582 794 / to escalate: bettina.kerschbaumer@privatklinik-ritzensee.at - +43 (0) 6582/794-4004",
    "ops_email": "office@privatklinik-ritzensee.at / trauma@privatklinik-ritzensee.at / pkr.radiologie@privatklinik-ritzensee.at / pkr.aufnahme@privatklinik-ritzensee.at",
    "website": "https://www.privatklinik-ritzensee.at/kontakt/",
    "comments": "Owner/type: PRIVATE. Opening hours: Montag-Donnerstag: 08:00 - 17:00; Freitag: 07:30 - 13.00 Uhr. PRIVATE OUTPATIENT / FIRST ASSESSMENT: 1/ Before referring the patient to the hospital, please contact the in-house practice: Ordination Dr. Guntmar Gradl Tel.: +43 (0)6582/794-3013 (If possible, preferably German-speaking communication) Additionally, please send an email to: trauma@privatklinik-ritzensee.at Opening hours: Mon-Thu: 08:00-17:00 & Fri: 07:30-13:00 2/ After receiving the estimated costs, the GOP must be sent to: trauma@privatklinik-ritzensee.at office@privatklinik-ritzensee.at pkr.radiologie@privatklinik-ritzensee.at --> Medical reports and invoices can be requested accordingly after treatment: trauma@privatklinik-ritzensee.a..."
  },
  {
    "id": "austria-schwarzach-im-pongau-kardinal-schwarzenberg-klinikum",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Kardinal Schwarzenberg Klinikum",
    "type": "Hospital/Clinic",
    "agreement": "Agreement signed",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Schwarzach im Pongau",
    "region": "Salzburg",
    "lat": 47.32144,
    "lon": 13.152851,
    "address": "Kardinal Schwarzenbergplatz 1, 5620 Schwarzach im Pongau, Austria",
    "ops_phone": "TEL 43 6415 7101-0 / ppa. Hermann Hirscher  Verwaltungsdirektor  Leitung Finanz- und Rechnungswesen  TEL  +43 6415 7101-2266  MAIL  hermann.hirscher@ks-klinikum.at",
    "ops_email": "aufnahme.postfach@ks-klinikum.at / postfach.patientenverrechnung@ks-klinikum.at",
    "website": "https://www.ks-klinikum.at/de/",
    "comments": "Owner/type: PUBLIC. PUBLIC: OUTPATIENT: pay and & claim only / MR will be given directly to the PAT (no GOP will be accepted) --> the hospital will accept all kind of credit cards INPATIENT: (no agreement signed) but they will accept our GOP: pls send it to: aufnahme.postfach@ks-klinikum.at & postfach.patientenverrechnung@ks-klinikum.at (office is only available during normal busniess hours) --> MR will be ready 2 days after admission --> no medical updates will be doncw --> only DCMR MEDEX: Invoice will be ready - 3 weeks after discharge MAIN FOCUS: general hospital & Accident and sports trauma"
  },
  {
    "id": "austria-saalbach-saalmed-saalbach-hinterglemm",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Saalmed Saalbach/Hinterglemm",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Saalbach",
    "region": "Salzburg",
    "lat": 47.3880974,
    "lon": 12.647329,
    "address": "Forstwiesenweg 776, 5753 Saalbach, Austria",
    "ops_phone": "06541 6287",
    "ops_email": "office@saalmed.at",
    "website": "http://www.saalmed.at",
    "comments": "Owner/type: PRIVATE. PRIVATE - PAY & CLAIM ONLY MAIN FOCUS: Accident and sports trauma"
  },
  {
    "id": "austria-radstadt-krankenanstalt-dr-aufmesser-radstadt",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Krankenanstalt Dr. Aufmesser Radstadt",
    "type": "Hospital/Clinic",
    "agreement": "Agreement signed",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Radstadt",
    "region": "Salzburg",
    "lat": 47.3854151,
    "lon": 13.4671564,
    "address": "Judenbuehel 3, 5500 Radstadt, Austria",
    "ops_phone": "Tel.: +43 6452 7501",
    "ops_email": "radstadt@aufmesser.at / buero@aufmesser.at",
    "website": "https://www.aufmesser.at/sportklinik/",
    "comments": "Owner/type: PRIVATE. Opening hours: MO: 07:30-11:30 und 16-18 Uhr DI: 07:30-11:30 und 16-18 Uhr MI: 07:30-11:30 und 14-16 Uhr DO: 07:30-11:30 und 14-16 Uhr FR: 07:30-11:30 Uhr. PRIVATE - no agreement signed but they accept our GOP MR & MEDEX can be requested: buero@aufmesser.at GOP need to be sent to: buero@aufmesser.at MAIN FOCUS: Accident and sports trauma"
  },
  {
    "id": "austria-obertauern-krankenanstalt-dr-aufmesser-obertauern",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Krankenanstalt Dr. Aufmesser Obertauern",
    "type": "Hospital/Clinic",
    "agreement": "Agreement signed",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Obertauern",
    "region": "Salzburg",
    "lat": 47.2480677,
    "lon": 13.557925,
    "address": "Roemerstrasse 54, 5562 Obertauern, Austria",
    "ops_phone": "Telefon: +43-6456-7298",
    "ops_email": "obertauern@aufmesser.at / buero@aufmesser.at",
    "website": "https://www.aufmesser.at/impressum/",
    "comments": "Owner/type: PRIVATE. Opening hours: MO bis SA: 9:00 - 12:00 Uhr & 14:00 - 17:00 Uhr SO & Feiertag: 10:00 - 12:00 Uhr & 14:00 - 17:00 Uhr. PRIVATE - no agreement signed but they accept our GOP MR & MEDEX can be requested: buero@aufmesser.at GOP need to be sent to: buero@aufmesser.at MAIN FOCUS: Accident and sports trauma"
  },
  {
    "id": "austria-oberndorf-bei-salzburg-oberndorf-kh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Oberndorf KH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement signed",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Oberndorf bei Salzburg",
    "region": "Salzburg",
    "lat": 47.9364144,
    "lon": 12.9475171,
    "address": "Paracelsusstrasse 37, 5110 Oberndorf bei Salzburg, Austria",
    "ops_phone": "06272 4334 601",
    "ops_email": "info@kh-oberndorf.at / j.silberer@kh-oberndorf.at / B.Bruckmoser@kh-oberndorf.at",
    "website": "https://www.krankenhaus-oberndorf.at/",
    "comments": "Owner/type: PUBLIC. PUBLIC - will accept our GOP / no agreement signed - GOP: please send GOP to b.bruckmoser@kh-oberndorf.at & j.silberer@kh-oberndorf.at MR & MEDEX can be requested through b.bruckmoser@kh-oberndorf.at & j.silberer@kh-oberndorf.at MAIN FOCUS: general hospital & Accident and sports trauma"
  },
  {
    "id": "austria-salzburg-landeskrankenhaus-salzburg-salk-gruppe",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Landeskrankenhaus Salzburg (SALK-Gruppe)",
    "type": "Hospital/Clinic",
    "agreement": "GOP accepted - no DBA",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Salzburg",
    "region": "Salzburg",
    "lat": 47.8062316,
    "lon": 13.0304065,
    "address": "Muellner Hauptstrasse 48, 5020 Salzburg, Austria",
    "ops_phone": "05 7255 58838",
    "ops_email": "invoice@salk.at / krankengeschichtenanforderung@salk.at / ambulanzabarechnung@salk.at / abrechnung@salk.at",
    "website": "https://salk.at/Landeskrankenhaus.html",
    "comments": "Owner/type: PUBLIC. PUBLIC OUTPATIENT: The patient has to pay the costs directly. However, we can request a copy of the invoice: ambulanzabarechnung@salk.at MR: krankengeschichtenanforderung@salk.at INPATIENT: They will accept our GOP. Billing contact: GOP & MEDEX: abrechnung@salk.at MR: abrechnung@salk.at & krankengeschichtenanforderung@salk.at Please note that in all cases, they require a signed release of medical information form in advance before they are able to share any medical information with us. MAIN FOCUS: general hospital & Accident and sports trauma"
  },
  {
    "id": "austria-hallein-hallein-lkl-salk-gruppe",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Hallein LKL (SALK-Gruppe)",
    "type": "Hospital/Clinic",
    "agreement": "GOP accepted - no DBA",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Hallein",
    "region": "Salzburg",
    "lat": 47.6853116,
    "lon": 13.1126818,
    "address": "Buergermeisterstrasse 34, 5400 Hallein, Austria",
    "ops_phone": "05 72 55 44",
    "ops_email": "invoice@salk.at / krankengeschichtenanforderung@salk.at / ambulanzabarechnung@salk.at / abrechnung@salk.at",
    "website": "https://salk.at/Landesklinik_Hallein.html",
    "comments": "Owner/type: PUBLIC. PUBLIC OUTPATIENT: The patient has to pay the costs directly. However, we can request a copy of the invoice: ambulanzabarechnung@salk.at MR: krankengeschichtenanforderung@salk.at INPATIENT: They will accept our GOP. Billing contact: GOP & MEDEX: abrechnung@salk.at MR: abrechnung@salk.at & krankengeschichtenanforderung@salk.at Please note that in all cases, they require a signed release of medical information form in advance before they are able to share any medical information with us. MAIN FOCUS: general hospital & Accident and sports trauma"
  },
  {
    "id": "austria-tamsweg-landesklinik-tamsweg-salk-gruppe",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Landesklinik Tamsweg (SALK-Gruppe)",
    "type": "Hospital/Clinic",
    "agreement": "GOP accepted - no DBA",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Tamsweg",
    "region": "Salzburg",
    "lat": 47.1291685,
    "lon": 13.8092397,
    "address": "Bahnhofstrasse 7, 5580 Tamsweg, Austria",
    "ops_phone": "05 7255-47",
    "ops_email": "invoice@salk.at / krankengeschichtenanforderung@salk.at / ambulanzabarechnung@salk.at / abrechnung@salk.at",
    "website": "https://salk.at/landesklinik-tamsweg/",
    "comments": "Owner/type: PUBLIC. PUBLIC OUTPATIENT: The patient has to pay the costs directly. However, we can request a copy of the invoice: ambulanzabarechnung@salk.at MR: krankengeschichtenanforderung@salk.at INPATIENT: They will accept our GOP. Billing contact: GOP & MEDEX: abrechnung@salk.at MR: abrechnung@salk.at & krankengeschichtenanforderung@salk.at Please note that in all cases, they require a signed release of medical information form in advance before they are able to share any medical information with us. MAIN FOCUS: general hospital & Accident and sports trauma"
  },
  {
    "id": "austria-st-veit-im-pongau-st-veit-lkl-salk-gruppe",
    "source": "austria-hospital-import-2026-06-19",
    "name": "St Veit LKL (SALK-Gruppe)",
    "type": "Hospital/Clinic",
    "agreement": "GOP accepted - no DBA",
    "main_country": "Austria",
    "country": "Austria",
    "city": "St. Veit im Pongau",
    "region": "Salzburg",
    "lat": 47.3312817,
    "lon": 13.1627545,
    "address": "St. Veiter-Strasse 46, 5621 St. Veit im Pongau, Austria",
    "ops_phone": "05 7255 46",
    "ops_email": "invoice@salk.at / krankengeschichtenanforderung@salk.at / ambulanzabarechnung@salk.at / abrechnung@salk.at",
    "website": "https://salk.at/Landesklinik_St_Veit.html",
    "comments": "Owner/type: PUBLIC. PUBLIC OUTPATIENT: The patient has to pay the costs directly. However, we can request a copy of the invoice: ambulanzabarechnung@salk.at MR: krankengeschichtenanforderung@salk.at INPATIENT: They will accept our GOP. Billing contact: GOP & MEDEX: abrechnung@salk.at MR: abrechnung@salk.at & krankengeschichtenanforderung@salk.at Please note that in all cases, they require a signed release of medical information form in advance before they are able to share any medical information with us. MAIN FOCUS: general hospital & Accident and sports trauma"
  },
  {
    "id": "austria-lech-am-arlberg-dr-rhomberg-unfallsanatorium",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Dr. Rhomberg Unfallsanatorium",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Lech am Arlberg",
    "region": "Vorarlberg",
    "lat": 47.2160247,
    "lon": 10.1496636,
    "address": "Oberstubenbach 439, 6764 Lech am Arlberg, Austria",
    "ops_phone": "05583 2234",
    "website": "https://www.drrhomberg.at",
    "comments": "Owner/type: PRIVATE. Opening hours: Montag bis Freitag: von 9.00 Uhr bis 17.00 Uhr Samstag, Sonntag und Feiertag von 10.00 Uhr bis 17.00 Uhr. PRIVATE - PAY & CLAIM ONLY MAIN FOCUS: Accident and sports trauma"
  },
  {
    "id": "austria-rankweil-rankweil-lkh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Rankweil LKH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Rankweil",
    "region": "Vorarlberg",
    "lat": 47.2599777,
    "lon": 9.648631,
    "address": "Valdunastrasse 16, 6830 Rankweil, Austria",
    "ops_phone": "05522 403 0",
    "ops_email": "office@lkhr.at",
    "website": "https://www.landeskrankenhaus.at/gesundheitsunternehmen/standorte/lkh-rankweil",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-schruns-chirurgie-sport-dr-schenk-sanatorium-dr-schenk-gmbh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Chirurgie & Sport Dr. Schenk - Sanatorium Dr. Schenk GmbH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Schruns",
    "region": "Vorarlberg",
    "lat": 47.0737764,
    "lon": 9.9133496,
    "address": "Montafonerstrasse 29, 6780 Schruns, Austria",
    "ops_phone": "05556 74 000",
    "ops_email": "anmeldung@dr-schenk.at",
    "website": "https://www.dr-schenk.at/klinik/sport-chirurgie-ischgl/",
    "comments": "Owner/type: PRIVATE. PRIVATE - PAY & CLAIM ONLY MAIN FOCUS: Accident and sports trauma"
  },
  {
    "id": "austria-graz-graz-lkh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Graz LKH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Graz",
    "region": "Steiermark",
    "lat": 47.0797067,
    "lon": 15.4655977,
    "address": "Auenbrugger Platz 1, 8036 Graz, Austria",
    "ops_phone": "0316 385 0",
    "ops_email": "sekretariatfmpm@uniklinikum.kages.at",
    "website": "https://www.uniklinikumgraz.at/",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-wien-landstrasse-kl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Landstrasse KL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Wien",
    "region": "Wien",
    "lat": 48.1958853,
    "lon": 16.3912653,
    "address": "Juchgasse 25, 1030 Wien, Austria",
    "ops_phone": "01 711 65 0",
    "website": "https://klinik-landstrasse.gesundheitsverbund.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-wien-favoriten-kl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Favoriten KL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Wien",
    "region": "Wien",
    "lat": 48.1735013,
    "lon": 16.3505485,
    "address": "Kundratstrasse 3, 1100 Wien, Austria",
    "ops_phone": "01 601 91 0",
    "website": "https://klinik-favoriten.gesundheitsverbund.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-wien-hietzing-kl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Hietzing KL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Wien",
    "region": "Wien",
    "lat": 48.1725099,
    "lon": 16.2738882,
    "address": "Wolkersbergenstrasse 1, 1130 Wien, Austria",
    "ops_phone": "01 801 10 0",
    "website": "https://klinik-hietzing.gesundheitsverbund.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-wien-hanusch-kh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Hanusch KH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Wien",
    "region": "Wien",
    "lat": 48.1995552,
    "lon": 16.291749,
    "address": "Heinrich-Collin-Strasse 30, 1140 Wien, Austria",
    "ops_phone": "01 910 21 0",
    "website": "https://www.gesundheitskasse.at/cdscontent/?contentid=10007.875760&portal=oegkhanuschkrankenhausportal",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-wien-floridsdorf-kl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Floridsdorf KL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Wien",
    "region": "Wien",
    "lat": 48.270136,
    "lon": 16.404719,
    "address": "Bruenner Strasse 73, 1210 Wien, Austria",
    "ops_phone": "01 277 00 0",
    "website": "https://klinik-floridsdorf.gesundheitsverbund.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-wien-donaustadt-kl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Donaustadt KL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Wien",
    "region": "Wien",
    "lat": 48.2190749,
    "lon": 16.4639524,
    "address": "Langobardenstrasse 122, 1220 Wien, Austria",
    "ops_phone": "01 288 02 0",
    "website": "https://klinik-donaustadt.gesundheitsverbund.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-wien-akh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "AKH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Wien",
    "region": "Wien",
    "lat": 48.2200439,
    "lon": 16.3479083,
    "address": "Waehringer Guertel 18-20, 1090 Wien, 1090 Wien, Austria",
    "ops_phone": "43(0)1404000",
    "website": "https://www.akhwien.at/default.aspx?pid=80",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-kittsee-kittsee-kl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Kittsee KL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Kittsee",
    "region": "Burgenland",
    "lat": 48.0927076,
    "lon": 17.0663027,
    "address": "Hauptplatz 3, 2421 Kittsee, Austria",
    "ops_phone": "05 7979 35000",
    "website": "https://www.gesundheit-burgenland.at/kittsee",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-eisenstadt-eisenstadt-bbr-kh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Eisenstadt BBR KH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Eisenstadt",
    "region": "Burgenland",
    "lat": 47.8476293,
    "lon": 16.513804,
    "address": "Johannes von Gott-Platz 1, 7000 Eisenstadt, Austria",
    "ops_phone": "02682 601 0",
    "website": "https://www.barmherzige-brueder.at/portal/eisenstadt/home",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-oberpullendorf-oberpullendorf-kl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Oberpullendorf KL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Oberpullendorf",
    "region": "Burgenland",
    "lat": 47.5070439,
    "lon": 16.5093074,
    "address": "Spitalstrasse 32, 7350 Oberpullendorf, Austria",
    "ops_phone": "05 7979 34000",
    "website": "https://www.gesundheit-burgenland.at/oberpullendorf",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-oberwart-oberwart-kl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Oberwart KL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Oberwart",
    "region": "Burgenland",
    "lat": 47.2788603,
    "lon": 16.2062371,
    "address": "Dornburggasse 90, 7400 Oberwart, Austria",
    "ops_phone": "05 7979 32000",
    "website": "https://www.gesundheit-burgenland.at/oberwart",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-guessing-guessing-kl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Guessing KL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Guessing",
    "region": "Burgenland",
    "lat": 47.0466471,
    "lon": 16.3179834,
    "address": "Grazer Strasse 13, 7540 Guessing, Austria",
    "ops_phone": "05 7979 31000",
    "website": "https://www.gesundheit-burgenland.at/guessing",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-hollabrunn-hollabrunn-lkl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Hollabrunn LKL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Hollabrunn",
    "region": "Niederoesterreich",
    "lat": 48.5627939,
    "lon": 16.0907506,
    "address": "Robert Loeffler-Strasse 20, 2020 Hollabrunn, Austria",
    "ops_phone": "02952 2275 0",
    "website": "https://hollabrunn.lknoe.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-hainburg-an-der-donau-hainburg-lkl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Hainburg LKL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Hainburg an der Donau",
    "region": "Niederoesterreich",
    "lat": 48.1433463,
    "lon": 16.9578648,
    "address": "Hofmeisterstrasse 70, 2410 Hainburg an der Donau, Austria",
    "ops_phone": "02165 90501 203",
    "website": "https://hainburg.lknoe.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-neunkirchen-neunkirchen-univkl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Neunkirchen UnivKL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Neunkirchen",
    "region": "Niederoesterreich",
    "lat": 47.7262939,
    "lon": 16.0870537,
    "address": "Peischinger Strasse 19, 2620 Neunkirchen, Austria",
    "ops_phone": "02635 602",
    "website": "https://neunkirchen.lknoe.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-wiener-neustadt-wiener-neustadt-univkl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Wiener Neustadt UnivKL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Wiener Neustadt",
    "region": "Niederoesterreich",
    "lat": 47.8150383,
    "lon": 16.2481971,
    "address": "Matthias Corviniusring 3-5, 2700 Wiener Neustadt, Austria",
    "ops_phone": "02622 321 0",
    "website": "https://wienerneustadt.lknoe.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-grimmenstein-hochegg-univkl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Hochegg UnivKL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Grimmenstein",
    "region": "Niederoesterreich",
    "lat": 47.6164069,
    "lon": 16.0872344,
    "address": "Hocheggerstrasse 88, 2840 Grimmenstein, Austria",
    "ops_phone": "02644 6300 0",
    "website": "https://hochegg.lknoe.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-scheibbs-scheibbs-lkl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Scheibbs LKL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Scheibbs",
    "region": "Niederoesterreich",
    "lat": 48.0118909,
    "lon": 15.1629839,
    "address": "Eisenwurzenstrasse 26, 3270 Scheibbs, Austria",
    "ops_phone": "07482 404 0",
    "website": "https://scheibbs.lknoe.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-amstetten-amstetten-lkl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Amstetten LKL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Amstetten",
    "region": "Niederoesterreich",
    "lat": 48.1276038,
    "lon": 14.8817819,
    "address": "Krankenhausstrasse 21, 3300 Amstetten, Austria",
    "ops_phone": "07472 9004 0",
    "website": "https://amstetten.lknoe.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-waidhofen-an-der-ybbs-waidhofen-ybbs-lkl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Waidhofen/Ybbs LKL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Waidhofen an der Ybbs",
    "region": "Niederoesterreich",
    "lat": 47.9527974,
    "lon": 14.7881297,
    "address": "Ybbsitzer Strasse 112, 3340 Waidhofen an der Ybbs, Austria",
    "ops_phone": "07442 9004 0",
    "website": "https://waidhofen-ybbs.lknoe.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-melk-melk-lkl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Melk LKL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Melk",
    "region": "Niederoesterreich",
    "lat": 48.2266851,
    "lon": 15.3396525,
    "address": "Krankenhausstrasse 11, 3390 Melk, Austria",
    "ops_phone": "02752 9004",
    "website": "https://melk.lknoe.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-klosterneuburg-klosterneuburg-lkl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Klosterneuburg LKL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Klosterneuburg",
    "region": "Niederoesterreich",
    "lat": 48.3078238,
    "lon": 16.3237854,
    "address": "Kreutzergasse 12-14, 3400 Klosterneuburg, Austria",
    "ops_phone": "02243 9004 0",
    "website": "https://klosterneuburg.lknoe.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-tulln-an-der-donau-tulln-univkl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Tulln UnivKL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Tulln an der Donau",
    "region": "Niederoesterreich",
    "lat": 48.3221284,
    "lon": 16.0651486,
    "address": "Alter Ziegelweg 10, 3430 Tulln an der Donau, Austria",
    "ops_phone": "02272 601",
    "website": "https://tulln.lknoe.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-krems-an-der-donau-krems-univkl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Krems UnivKL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Krems an der Donau",
    "region": "Niederoesterreich",
    "lat": 48.4120285,
    "lon": 15.6155879,
    "address": "Mitterweg 10, 3500 Krems an der Donau, Austria",
    "ops_phone": "02732 804 0",
    "website": "https://krems.lknoe.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-linz-linz-bbr-kh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Linz BBR KH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Linz",
    "region": "Oberoesterreich",
    "lat": 48.3000151,
    "lon": 14.2879771,
    "address": "Seilerstaette 2, 4020 Linz, Austria",
    "ops_phone": "0732 7897 0",
    "website": "https://www.barmherzige-brueder.at/portal/linz/home",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-rohrbach-in-oberoesterreich-rohrbach-kl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Rohrbach KL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Rohrbach in Oberoesterreich",
    "region": "Oberoesterreich",
    "lat": 48.570976,
    "lon": 13.9823667,
    "address": "Krankenhausstrasse 1, 4150 Rohrbach in Oberoesterreich, Austria",
    "ops_phone": "050 554 77 0",
    "website": "https://www.ooeg.at/ro/",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-freistadt-freistadt-kl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Freistadt KL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Freistadt",
    "region": "Oberoesterreich",
    "lat": 48.4922403,
    "lon": 14.4979228,
    "address": "Krankenhausstrasse 1, 4240 Freistadt, Austria",
    "ops_phone": "050 554 76 0",
    "website": "https://www.ooeg.at/fr/",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-schaerding-schaerding-kl",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Schaerding KL",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Schaerding",
    "region": "Oberoesterreich",
    "lat": 48.455266,
    "lon": 13.4356651,
    "address": "Alfred-Kubin-Strasse 2, 4780 Schaerding, Austria",
    "ops_phone": "050 554 78 0",
    "website": "https://www.ooeg.at/sd/",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-ried-im-innkreis-ried-innkr-bhs-kh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Ried/Innkr BHS KH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Ried im Innkreis",
    "region": "Oberoesterreich",
    "lat": 48.2104583,
    "lon": 13.4931137,
    "address": "Schlossberg 1, 4910 Ried im Innkreis, Austria",
    "ops_phone": "07752 602 0",
    "website": "https://www.bhsried.at/",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-braunau-am-inn-braunau-st-josef-kh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Braunau St Josef KH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Braunau am Inn",
    "region": "Oberoesterreich",
    "lat": 48.2559762,
    "lon": 13.0328851,
    "address": "Ringstrasse 60, 5280 Braunau am Inn, Austria",
    "ops_phone": "07722 804 0",
    "website": "https://khbr.at/",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-kitzbuehel-tagesklinik-kitzbuehel",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Tagesklinik Kitzbuehel",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Kitzbuehel",
    "region": "Tirol",
    "lat": 47.4492104,
    "lon": 12.3920215,
    "address": "Hornweg 9, 6370 Kitzbuehel, Austria",
    "ops_phone": "05356 66866",
    "ops_email": "info@tk-kitz.net",
    "website": "https://www.tk-kitz.net/Tagesklinik-fuer-Unfallchirurgie-GmbH-Home_pid,59554,type,news.html",
    "comments": "Owner/type: PRIVATE. Opening hours: MO - FR 10 - 16 Uhr // SA, SO & FT 13 - 16 Uhr. PRIVATE - PAY & CLAIM ONLY MAIN FOCUS: Accident and sports trauma"
  },
  {
    "id": "austria-flirsch-dr-christian-klimmer",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Dr. Christian Klimmer",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Flirsch",
    "region": "Tirol",
    "lat": 47.1464067,
    "lon": 10.4162243,
    "address": "Flirsch 93, 6572 Flirsch, Austria",
    "ops_phone": "Tel. 0 54 47 . 94 100",
    "ops_email": "ordination@doktor-klimmer.at",
    "website": "https://www.doktor-klimmer.at/",
    "comments": "Owner/type: PUBLIC. PRIVATE - PAY & CLAIM ONLY MAIN FOCUS: Accident and sports trauma"
  },
  {
    "id": "austria-st-anton-am-arlberg-sportklinik-arlberg",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Sportklinik Arlberg",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "St. Anton am Arlberg",
    "region": "Tirol",
    "lat": 47.1257866,
    "lon": 10.2512841,
    "address": "Sollederweg 5, 6580 St. Anton am Arlberg, Austria",
    "ops_phone": "T: + 43 (0) 5446 42 666",
    "ops_email": "info@sportklinik-arlberg.at",
    "website": "http://www.sportklinik.arlberg.at",
    "comments": "Owner/type: PRIVATE. Opening hours: MO - FR 08:00 - 20:00 Uhr SA, SO, Feiertag 09:00 - 17:00 Uhr. PRIVATE - PAY & CLAIM ONLY MAIN FOCUS: Accident and sports trauma"
  },
  {
    "id": "austria-reutte-reutte-bkh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Reutte BKH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Reutte",
    "region": "Tirol",
    "lat": 47.4735773,
    "lon": 10.7123802,
    "address": "Krankenhausstrasse 39, 6600 Reutte, Austria",
    "ops_phone": "05672 601 0",
    "ops_email": "info@bkh-reutte.at",
    "website": "https://www.bkh-reutte.at/",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-lienz-lienz-bkh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Lienz BKH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Lienz",
    "region": "Tirol",
    "lat": 46.8350483,
    "lon": 12.7645992,
    "address": "Emanuel-von-Hibler-Strasse 5, 9900 Lienz, Austria",
    "ops_phone": "04852 606 0",
    "ops_email": "verwaltung@kh-lienz.at",
    "website": "https://www.kh-lienz.at/de/",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-dornbirn-dornbirn-kh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Dornbirn KH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Dornbirn",
    "region": "Vorarlberg",
    "lat": 47.4062965,
    "lon": 9.7402125,
    "address": "Lustenauer Strasse 4, 6850 Dornbirn, Austria",
    "ops_phone": "05572 303 0",
    "ops_email": "gerhard.amann@dornbirn.at",
    "website": "https://krankenhaus.dornbirn.at",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-bregenz-bregenz-lkh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Bregenz LKH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Bregenz",
    "region": "Vorarlberg",
    "lat": 47.4971503,
    "lon": 9.7458469,
    "address": "Carl-Pedenz-Strasse 2, 6900 Bregenz, Austria",
    "ops_phone": "05574 401 0",
    "ops_email": "office@lkhb.at",
    "website": "https://www.landeskrankenhaus.at/gesundheitsunternehmen/standorte/lkh-bregenz",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-st-veit-an-der-glan-st-veit-glan-bbr-kh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "St Veit/Glan BBR KH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "St. Veit an der Glan",
    "region": "Kaernten",
    "lat": 46.7692362,
    "lon": 14.3532845,
    "address": "Spitalgasse 26, 9300 St. Veit an der Glan, Austria",
    "ops_phone": "04212 499 0",
    "ops_email": "krankenhaus@bbstveit.at",
    "website": "https://www.barmherzige-brueder.at/portal/stveit/home",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-friesach-friesach-do-kh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Friesach DO KH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Friesach",
    "region": "Kaernten",
    "lat": 46.9465742,
    "lon": 14.4104054,
    "address": "St. Veiter Strasse 12, 9360 Friesach, Austria",
    "ops_phone": "04268 2691 0",
    "website": "https://www.dokh.at/",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-wolfsberg-wolfsberg-lkh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Wolfsberg LKH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Wolfsberg",
    "region": "Kaernten",
    "lat": 46.8332305,
    "lon": 14.8478892,
    "address": "Paul Hackhoferstrasse 9, 9400 Wolfsberg, Austria",
    "ops_phone": "04352 533 0",
    "website": "https://www.lkh-wo.at/",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
  {
    "id": "austria-spittal-an-der-drau-spittal-drau-kh",
    "source": "austria-hospital-import-2026-06-19",
    "name": "Spittal/Drau KH",
    "type": "Hospital/Clinic",
    "agreement": "Agreement pending",
    "main_country": "Austria",
    "country": "Austria",
    "city": "Spittal an der Drau",
    "region": "Kaernten",
    "lat": 46.8018094,
    "lon": 13.4911369,
    "address": "Billrothstrasse 1, 9800 Spittal an der Drau, Austria",
    "ops_phone": "04762 622 0",
    "ops_email": "office@khspittal.com",
    "website": "https://www.khspittal.com/",
    "comments": "Owner/type: PUBLIC. PUBLIC - No agreement in place / EHIC accepted OUTPATIENT: PAY & CLAIM only INPATIENT: We can try to issue our GOP; however, as there is no agreement in place, the case may also have to be handled on a PAY & CLAIM basis, depending on the total cost involved. MAIN FOCUS: General healthcare / general medical care."
  },
];
