const hospitalClinicProviders = [
  {
    id: "austria-tirol-kliniken-innsbruck",
    source: "austria-mymaps-gop-2026",
    name: "Tirol Kliniken Innsbruck",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Innsbruck",
    region: "Tirol",
    lat: 47.2615435,
    lon: 11.3851307,
    address: "Anichstrasse 35, A-6020 Innsbruck, Austria",
    network_manager: "Hansjoerg Schloegl (billing/GOP contact)",
    ops_phone: "+43 50 504-0",
    ops_email: "hansjoerg.schloegl@tirol-kliniken.at",
    website: "https://www.tirol-kliniken.at/page.cfm?vpath=standorte%2Flandeskrankenhaus-innsbruck",
    comments: "Public hospital - GOP accepted without signed DBA. Test for 2026: no direct contract, no cost estimate available, invoice normally issued after discharge. For inpatient admission email patient name and DOB to hansjoerg.schloegl@tirol-kliniken.at. Outpatient invoices are normally sent to the patient's home address; email the same contact to request invoice if Compass Point Assist covers. Full medical report is available at least 7 days after discharge via same contact. Repatriation must be discussed directly with treating ward doctor.",
  },
  {
    id: "austria-st-vinzenz-zams",
    source: "austria-mymaps-gop-2026",
    name: "St. Vinzenz Hospital Zams",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Zams",
    region: "Tirol",
    lat: 47.1614186,
    lon: 10.5940799,
    address: "Sanatoriumstrasse 43, A-6511 Zams, Austria",
    network_manager: "Patient billing / responsible medical office",
    ops_phone: "+43 5442 600",
    ops_email: "patient@krankenhaus-zams.at; unfall@krankenhaus-zams.at; office@krankenhaus-zams.at",
    website: "https://www.khzams.at/en/",
    comments: "Public hospital - GOP accepted without signed DBA for non-EHIC inpatient admission. For EHIC inpatient admissions, hospital daily allowance must be paid by patient at discharge. Medical reports are available after discharge only; requests must go to the responsible medical office/department, not patient billing. Trauma report contact from MyMaps notes: unfall@krankenhaus-zams.at. Patient billing contact from MyMaps notes: patient@krankenhaus-zams.at. Outpatient treatment may require partial payment on site and is generally pay-and-claim.",
  },
  {
    id: "austria-bkh-kufstein",
    source: "austria-mymaps-gop-2026",
    name: "Bezirkskrankenhaus Kufstein",
    type: "Hospital/Clinic",
    agreement: "GOP accepted case-by-case - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Kufstein",
    region: "Tirol",
    lat: 47.571767,
    lon: 12.1498691,
    address: "Endach 27, A-6330 Kufstein, Austria",
    network_manager: "Hospital administration",
    ops_phone: "+43 5372 6966-0",
    ops_email: "direktion@bkh-kufstein.at",
    website: "https://www.bkh-kufstein.at/de/kontakt.html",
    comments: "Public hospital - no signed direct billing contract. MyMaps notes say GOP/cost guarantee acceptance must be assessed case by case. Hospital requires a patient-signed release of medical information before sharing further details.",
  },
  {
    id: "austria-zellmed-medalp",
    source: "austria-mymaps-gop-2026",
    name: "Zellmed Medalp",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Zell am Ziller",
    region: "Tirol",
    lat: 47.2355047,
    lon: 11.8899151,
    address: "Stocklerfeld 6, 6280 Zell am Ziller, Austria",
    network_manager: "Medalp coordination",
    ops_phone: "+43 5282 4200; emergency +43 699 1611 9988",
    ops_email: "office@zellmed.at; info@medalp.com",
    website: "https://medalp.com/en/location/aerztehaus-zellmed/",
    comments: "GOP accepted without signed DBA. Medalp/Zellmed test phase for winter season 2026: GOP for first visit, EUR 1,000, should be sent before patient transfer to Medalp.",
  },
  {
    id: "austria-allgemeinpraxis-soelden-medalp",
    source: "austria-mymaps-gop-2026",
    name: "Allgemeinpraxis Soelden (Medalp Gruppe)",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Soelden",
    region: "Tirol",
    lat: 46.9697001,
    lon: 11.0096738,
    address: "Gemeindestrasse 1, 6450 Soelden, Austria",
    network_manager: "Medalp coordination",
    ops_phone: "+43 5254 2040; emergency +43 699 1611 9988",
    ops_email: "praxis-soelden@medalp.com; info@medalp.com",
    website: "https://medalp.com/en/location/allgemeinpraxis-soelden/",
    comments: "Private practice - GOP accepted without signed DBA. Medalp test phase for winter season 2026: GOP for first visit, EUR 1,000, should be sent before patient transfer to Medalp.",
  },
  {
    id: "austria-sportclinic-zillertal",
    source: "austria-mymaps-gop-2026",
    name: "Sportclinic Zillertal (Medalp Group)",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Mayrhofen",
    region: "Tirol",
    lat: 47.158721,
    lon: 11.846253,
    address: "Stillupklamm 830, 6290 Mayrhofen, Austria",
    network_manager: "Medalp coordination",
    ops_phone: "+43 5285 78485; emergency +43 699 1611 9988",
    ops_email: "office@sportclinic.at; info@medalp.com",
    website: "https://medalp.com/en/location/sportclinic-zillertal/",
    comments: "Private clinic - GOP accepted without signed DBA. Medalp test phase for winter season 2026: GOP for first visit, EUR 1,000, should be sent before patient transfer to Medalp. Source note dated 17/02/2026.",
  },
  {
    id: "austria-medalp-imst",
    source: "austria-mymaps-gop-2026",
    name: "medalp Imst - Medalp Sportclinic Imst GmbH",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Imst",
    region: "Tirol",
    lat: 47.214087,
    lon: 10.699678,
    address: "Medalp Platz 1, 6460 Imst, Austria",
    network_manager: "Medalp coordination",
    ops_phone: "+43 5418 51100; emergency +43 699 1611 9988",
    ops_email: "info@medalp.com",
    website: "https://medalp.com/en/location/sportclinic-imst/",
    comments: "Private clinic - GOP accepted without signed DBA. Medalp test phase for winter season 2026: GOP for first visit, EUR 1,000, should be sent before patient transfer to Medalp. Source note dated 17/02/2026.",
  },
  {
    id: "austria-medalp-sportclinic-soelden",
    source: "austria-mymaps-gop-2026",
    name: "medalp sportclinic Soelden - Gruppenpraxis fuer Unfallchirurgie Dr. Alois Schranz, Dr. Manfred Lener OG",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Soelden",
    region: "Tirol",
    lat: 46.9588407,
    lon: 11.0091484,
    address: "Dorfstrasse 160, 6450 Soelden, Austria",
    network_manager: "Medalp coordination",
    ops_phone: "+43 5254 30003; emergency +43 699 1611 9988",
    ops_email: "soelden@medalp.com; info@medalp.com",
    website: "https://medalp.com/en/location/sportclinic-soelden/",
    comments: "Private clinic - GOP accepted without signed DBA. Medalp test phase for winter season 2026: GOP for first visit, EUR 1,000, should be sent before patient transfer to Medalp. Source contact note: soelden@medalp.com, 18/02/2026.",
  },
  {
    id: "austria-medserfaus",
    source: "austria-mymaps-gop-2026",
    name: "Medserfaus Praxis - Hausapotheke",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Serfaus",
    region: "Tirol",
    lat: 47.0403035,
    lon: 10.5973277,
    address: "Dorfbahnstrasse 79, 6534 Serfaus, Austria",
    network_manager: "Mrs Koehle (CEO referral contact)",
    ops_phone: "+43 5476 53000; CEO mobile +43 650 6531053",
    ops_email: "info@medserfaus.at",
    website: "https://www.medserfaus.at/med-serfaus/kontakt-lage",
    comments: "Private practice - GOP accepted without signed DBA, but prompt payment is required. Before referral: contact CEO Mrs Koehle on +43 650 6531053, confirm internal handling, and email info@medserfaus.at with patient details. Medical report and invoice are provided after treatment. Serfaus is car-free, but access by car to this medical facility is permitted with parking directly in front.",
  },
  {
    id: "austria-lkh-villach",
    source: "austria-mymaps-gop-2026",
    name: "KABEG Landeskrankenhaus Villach",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Villach",
    region: "Kaernten",
    lat: 46.615932,
    lon: 13.85778,
    address: "Nikolaigasse 43, 9500 Villach, Austria",
    network_manager: "APMV / patient administration",
    ops_phone: "+43 4242 208-0",
    ops_email: "apmv@kabeg.at; lkh.villach@kabeg.at",
    website: "https://www.lkh-villach.at/",
    comments: "Public hospital - GOP accepted without signed DBA. Send GOP to apmv@kabeg.at. Final invoice expected 4-6 weeks after patient discharge. Source note dated 17/02/2026.",
  },
  {
    id: "austria-mrt-kaprun",
    source: "austria-mymaps-gop-2026",
    name: "MRT Kaprun - Kaprun Diagnostik - Facharztpraxen - Priv.-Doz. DDr. Karl Egger",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Kaprun",
    region: "Salzburg",
    lat: 47.2825959,
    lon: 12.7555589,
    address: "Tauern Spa Strasse 16, 5710 Kaprun, Austria",
    network_manager: "Kaprun Diagnostik team",
    ops_phone: "+43 6547 20505",
    ops_email: "info@mrt-kaprun.at",
    website: "https://www.mrt-kaprun.at/",
    comments: "Private diagnostic/specialist practice - GOP accepted without signed DBA. Send medical report and MEDEX requests to info@mrt-kaprun.at.",
  },
  {
    id: "austria-doc-around-the-town",
    source: "austria-mymaps-gop-2026",
    name: "Doc around the Town - Dr. Abdo Fakhreddine",
    type: "Hospital/Clinic",
    agreement: "GOP accepted - no DBA",
    main_country: "Austria",
    country: "Austria",
    city: "Vienna",
    region: "Wien",
    lat: 48.2084337,
    lon: 16.3683413,
    address: "Habsburgergasse 10/11, 1010 Wien, Austria",
    network_manager: "Dr. Abdo Fakhreddine",
    ops_phone: "+43 660 7077 684",
    ops_email: "office@docaroundthetown.com",
    website: "https://docaroundthetown.com/",
    comments: "Private doctor - GOP accepted without signed DBA. House-call and hotel-doctor visits only for Vienna and surrounding areas.",
  },
];