const germanyHospitalClinicProviders = [
  {
    id: "germany-24939-flensburg-malteser-foerdeklinikum-st-katharina-waldstrasse",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Malteser Foerdeklinikum St. Katharina - Waldstrasse site",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Flensburg",
    region: "Schleswig-Holstein",
    lat: 54.7922897,
    lon: 9.4207165,
    address: "Waldstrasse 17, 24939 Flensburg, Germany",
    ops_phone: "0461 816-0",
    ops_email: "krankenhaus.flensburg@malteser.org",
    website: "https://www.malteser-foerdeklinikum.de/",
    comments: "Beds listed: 317. Specialties: Surgery; ENT; Internal medicine; Geriatrics; Oral and maxillofacial surgery; Day clinic: geriatrics.",
  },
  {
    id: "germany-24113-kiel-helios-klinikum-kiel",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Helios Klinikum Kiel",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3045385,
    lon: 10.1168612,
    address: "Hamburger Chaussee 77, 24113 Kiel, Germany",
    ops_phone: "0431 7206-300",
    website: "https://www.helios-kliniken.de/klinik/kiel",
    comments: "Beds listed: 50. Specialties: Surgery; ENT; Oral and maxillofacial surgery; Neurosurgery; Orthopedics; Urology.",
  },
  {
    id: "germany-24116-kiel-klinik-flechsig",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinik Flechsig",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3228203,
    lon: 10.1163371,
    address: "Chemnitzstrasse 33, 24116 Kiel, Germany",
    ops_phone: "0431 3397100",
    ops_email: "info@kliniik-flechsig.de",
    website: "https://www.klinik-flechsig.de",
    comments: "Beds listed: 30. Specialties: ENT.",
  },
  {
    id: "germany-24106-kiel-lubinus-clinicum",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Lubinus Clinicum",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3529232,
    lon: 10.1167164,
    address: "Steenbeker Weg 25, 24106 Kiel, Germany",
    ops_phone: "0431 388-0",
    ops_email: "info@mvz-lubinus.de",
    website: "https://www.lubinus-kliniken.de/",
    comments: "Beds listed: 199. Specialties: Surgery; Orthopedics.",
  },
  {
    id: "germany-24105-kiel-nordblick-augenklinik-bellevue",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "nordBLICK Augenklinik Bellevue",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3456265,
    lon: 10.1492353,
    address: "Lindenallee 21-23, 24105 Kiel, Germany",
    ops_phone: "0431 30108-0",
    ops_email: "uthoff@augenklinik-bellevue.de",
    website: "https://www.augenklinik-bellevue.de",
    comments: "Beds listed: 18. Specialties: Ophthalmology.",
  },
  {
    id: "germany-24116-kiel-park-klinik",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Park-Klinik Kiel",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3266908,
    lon: 10.1257264,
    address: "Goethestrasse 11, 24116 Kiel, Germany",
    ops_phone: "0431 5909-0",
    ops_email: "carecenter@park-klinik-kiel.de",
    website: "https://www.park-klinik-kiel.de",
    comments: "Beds listed: 46. Specialties: Surgery; Gynecology and obstetrics; ENT; Internal medicine.",
  },
  {
    id: "germany-24114-kiel-kieler-fenster-psychiatric-day-clinic",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Kieler Fenster Psychiatric Day Clinic",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3085101,
    lon: 10.1263,
    address: "Alte Luebecker Chaussee 1, 24114 Kiel, Germany",
    ops_phone: "0431 649802-0",
    ops_email: "tagesklinik@kieler-fenster.de",
    website: "https://www.kieler-fenster.de",
    comments: "Specialties: Day clinic: psychiatry.",
  },
  {
    id: "germany-24149-kiel-schmerzklinik-kiel",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Schmerzklinik Kiel",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3288942,
    lon: 10.1838107,
    address: "Heikendorfer Weg 9-27, 24149 Kiel, Germany",
    ops_phone: "0431 20099-0",
    ops_email: "Kiel@Schmerzklinik.de",
    website: "https://schmerzklinik.de/",
    comments: "Beds listed: 80. Specialties: Neurology.",
  },
  {
    id: "germany-24116-kiel-staedtisches-krankenhaus-kiel",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Staedtisches Krankenhaus Kiel",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3228203,
    lon: 10.1163371,
    address: "Chemnitzstrasse 33, 24116 Kiel, Germany",
    ops_phone: "0431 1697-0",
    ops_email: "info@krankenhaus-kiel.de",
    website: "https://www.krankenhaus-kiel.de",
    comments: "Beds listed: 678. Specialties: Surgery; Gynecology and obstetrics; Internal medicine; Geriatrics; Pediatrics; Urology; Other specialties; Day clinic: geriatrics.",
  },
  {
    id: "germany-24105-kiel-university-medical-center-schleswig-holstein-kiel",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "University Medical Center Schleswig-Holstein - Kiel Campus",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3278096,
    lon: 10.1417471,
    address: "Brunswiker Strasse 10, 24105 Kiel, Germany",
    ops_phone: "0431 597-0",
    ops_email: "info@uksh.de",
    website: "https://www.uksh.de",
    comments: "Beds listed: 1107. Specialties: Ophthalmology; Surgery; Trauma/accident surgery; Gynecology and obstetrics; Gynecology; Obstetrics; ENT; Dermatology and venereology; Cardiac surgery; Internal medicine; Hematology/oncology; Cardiology.",
  },
  {
    id: "germany-23566-luebeck-red-cross-hospital-geriatrics-centre",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Red Cross Hospital Luebeck - Geriatrics Centre",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Luebeck",
    region: "Schleswig-Holstein",
    lat: 53.8730757,
    lon: 10.7085117,
    address: "Marlistrasse 10, 23566 Luebeck, Germany",
    ops_phone: "0451 6202-0",
    ops_email: "info.TZ@drk-schwhl.de",
    website: "https://www.drk-schwesternschaft-luebeck.de/",
    comments: "Beds listed: 164. Specialties: Geriatrics; Day clinic: geriatrics.",
  },
  {
    id: "germany-23538-luebeck-university-medical-center-schleswig-holstein-luebeck",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "University Medical Center Schleswig-Holstein - Luebeck Campus",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Luebeck",
    region: "Schleswig-Holstein",
    lat: 53.8358374,
    lon: 10.7087465,
    address: "Ratzeburger Allee 160, 23538 Luebeck, Germany",
    ops_phone: "0451 500-0",
    ops_email: "info@uk-sh.de",
    website: "https://www.uksh.de",
    comments: "Beds listed: 1049. Specialties: Ophthalmology; Surgery; Trauma/accident surgery; Gynecology and obstetrics; Gynecology; Obstetrics; ENT; Dermatology and venereology; Cardiac surgery; Internal medicine; Cardiology; Pulmonology.",
  },
  {
    id: "germany-23560-luebeck-sana-kliniken-luebeck-south-hospital",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Sana Kliniken Luebeck - South Hospital",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Luebeck",
    region: "Schleswig-Holstein",
    lat: 53.8488707,
    lon: 10.6879537,
    address: "Kronsforder Allee 71/73, 23560 Luebeck, Germany",
    ops_phone: "0451 585-01",
    ops_email: "info@sana-luebeck.de",
    website: "https://www.sana-luebeck.de",
    comments: "Specialties: Surgery; Internal medicine; Hematology/oncology; Neurology; Urology; Other specialties.",
  },
  {
    id: "germany-25541-brunsbuettel-westkuestenklinikum-brunsbuettel",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Westkuestenklinikum Brunsbuettel",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Brunsbuettel",
    region: "Schleswig-Holstein",
    lat: 53.8999702,
    lon: 9.1462558,
    address: "Delbrueckstr. 2, 25541 Brunsbuettel, Germany",
    ops_phone: "04852 980-0",
    website: "https://www.westkuestenklinikum.de/",
    comments: "Specialties: Surgery; Internal medicine; Geriatrics; Urology; Day clinic: internal medicine; Day clinic: geriatrics; Day clinic: psychiatry.",
  },
  {
    id: "germany-25746-heide-westkuestenklinikum-heide",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Westkuestenklinikum Heide",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Heide",
    region: "Schleswig-Holstein",
    lat: 54.1991651,
    lon: 9.0810799,
    address: "Esmarchstr. 50, 25746 Heide, Germany",
    ops_phone: "0481 785-0",
    ops_email: "info@wkk-hei.de",
    website: "https://www.westkuestenklinikum.de/",
    comments: "Specialties: Surgery; Vascular surgery; Trauma/accident surgery; Gynecology and obstetrics; ENT; Internal medicine; Geriatrics; Pediatrics; Neurosurgery; Neurology; Nuclear medicine; Psychiatry.",
  },
  {
    id: "germany-21502-geesthacht-krankenhaus-geesthacht-vitalcampus-geesthacht",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Krankenhaus Geesthacht / Vitalcampus Geesthacht",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Geesthacht",
    region: "Schleswig-Holstein",
    lat: 53.4315254,
    lon: 10.3858089,
    address: "Am Runden Berge 3, 21502 Geesthacht, Germany",
    ops_phone: "04152 179-0",
    ops_email: "info@johanniter-krankenhaus.de",
    website: "https://www.johanniter.de/johanniter-kliniken/krankenhaus-geesthacht/",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Internal medicine; Psychiatry; Psychotherapy; Day clinic: psychiatry; Day clinic: psychotherapy.",
  },
  {
    id: "germany-23909-ratzeburg-drk-hospital-moelln-ratzeburg",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "DRK Hospital Moelln-Ratzeburg",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Ratzeburg",
    region: "Schleswig-Holstein",
    lat: 53.6898388,
    lon: 10.778847,
    address: "Roepersberg 2, 23909 Ratzeburg, Germany",
    ops_phone: "04541 884-01",
    ops_email: "info@drk-krankenhaus.de",
    website: "https://www.drk-krankenhaus.de",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Gynecology; Obstetrics; Internal medicine; Urology.",
  },
  {
    id: "germany-23909-ratzeburg-ratzeburg-geriatric-clinic",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Ratzeburg Geriatric Clinic",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Ratzeburg",
    region: "Schleswig-Holstein",
    lat: 53.6825424,
    lon: 10.7681319,
    address: "Roepersberg 47, 23909 Ratzeburg, Germany",
    ops_phone: "04541 13-3700",
    ops_email: "info@geriatrie-ratzeburg.de",
    website: "https://www.geriatrie-ratzeburg.de",
    comments: "Specialties: Geriatrics; Day clinic: geriatrics.",
  },
  {
    id: "germany-25813-husum-klinik-dr-winkler-amedes-clinic-husum",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinik Dr. Winkler - Amedes Clinic Husum",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Husum",
    region: "Schleswig-Holstein",
    lat: 54.4800559,
    lon: 9.0558461,
    address: "Brinckmannstr. 6, 25813 Husum, Germany",
    ops_phone: "04841 6911-0",
    ops_email: "klinik-winkler@foni.de",
    website: "https://www.amedes-klinik-husum.de/",
    comments: "Specialties: Surgery.",
  },
  {
    id: "germany-25813-husum-klinikum-nordfriesland-husum-hospital",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinikum Nordfriesland - Husum Hospital",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Husum",
    region: "Schleswig-Holstein",
    lat: 54.4833008,
    lon: 9.0502002,
    address: "Erichsenweg 16, 25813 Husum, Germany",
    ops_phone: "04841 660-0",
    ops_email: "husum@klinikum-nf.de",
    website: "https://www.klinikum-nf.de",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Gynecology; Obstetrics; Internal medicine; Geriatrics; Urology; Day clinic: geriatrics.",
  },
  {
    id: "germany-25899-niebuell-klinikum-nordfriesland-niebuell-hospital",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinikum Nordfriesland - Niebuell Hospital",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Niebuell",
    region: "Schleswig-Holstein",
    lat: 54.7930609,
    lon: 8.8436755,
    address: "Gather Landstr. 75, 25899 Niebuell, Germany",
    ops_phone: "04661 151",
    website: "https://www.klinikum-nf.de",
    comments: "Specialties: Surgery; ENT; Internal medicine; Geriatrics; Day clinic: internal medicine; Day clinic: geriatrics.",
  },
  {
    id: "germany-25938-wyk-auf-foehr-klinikum-nordfriesland-foehr-amrum-island-clinic",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinikum Nordfriesland - Foehr-Amrum Island Clinic",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Wyk auf Foehr",
    region: "Schleswig-Holstein",
    lat: 54.6853714,
    lon: 8.5642967,
    address: "Rebbelstieg 24, 25938 Wyk auf Foehr, Germany",
    ops_phone: "04681 48-0",
    ops_email: "wyk@klinikum-nf.de",
    website: "https://www.klinikum-nf.de",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Internal medicine.",
  },
  {
    id: "germany-25980-westerland-asklepios-nordseeklinik-westerland",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Asklepios Nordseeklinik Westerland",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Westerland",
    region: "Schleswig-Holstein",
    lat: 54.9254688,
    lon: 8.3132852,
    address: "Norderstrasse 81, 25980 Westerland, Germany",
    ops_phone: "04651 84-1201",
    ops_email: "sylt@asklepios.de",
    website: "https://www.asklepios.com/sylt",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Dermatology and venereology; Internal medicine; Urology.",
  },
  {
    id: "germany-23611-bad-schwartau-helios-agnes-karll-hospital-bad-schwartau",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Helios Agnes Karll Hospital Bad Schwartau",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Bad Schwartau",
    region: "Schleswig-Holstein",
    lat: 53.9224163,
    lon: 10.6938415,
    address: "Am Hochkamp 21, 23611 Bad Schwartau, Germany",
    ops_phone: "0451 2007-0",
    ops_email: "postmaster@badschwartau.helios-kliniken.de",
    website: "https://www.helios-kliniken.de/badschwartau",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Gynecology; ENT; Internal medicine; Oral and maxillofacial surgery; Neurosurgery; Orthopedics; Urology.",
  },
  {
    id: "germany-23701-eutin-sankt-elisabeth-hospital-eutin",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Sankt Elisabeth Hospital Eutin",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Eutin",
    region: "Schleswig-Holstein",
    lat: 54.1384268,
    lon: 10.6106838,
    address: "Ploener Str. 42, 23701 Eutin, Germany",
    ops_phone: "04521 802-0",
    ops_email: "info@sek-eutin.de",
    website: "https://sek-eutin.de/",
    comments: "Specialties: Internal medicine; Geriatrics; Other specialties; Day clinic: geriatrics.",
  },
  {
    id: "germany-23714-bad-malente-gremsmuehlen-august-bier-clinic-neurology-and-neurorehabilitation",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "August-Bier Clinic - Neurology and Neurorehabilitation",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Bad Malente-Gremsmuehlen",
    region: "Schleswig-Holstein",
    lat: 54.1643762,
    lon: 10.5477242,
    address: "Diekseepromenade 7-11, 23714 Bad Malente-Gremsmuehlen, Germany",
    ops_phone: "04523 405-0",
    ops_email: "info@august-bier-klinik.de",
    website: "https://www.august-bier-klinik.de",
    comments: "Specialties: Neurology.",
  },
  {
    id: "germany-23714-bad-malente-gremsmuehlen-curtius-clinic-psychosomatic-medicine-and-psychotherapy",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Curtius Clinic - Psychosomatic Medicine and Psychotherapy",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Bad Malente-Gremsmuehlen",
    region: "Schleswig-Holstein",
    lat: 54.1718808,
    lon: 10.5661185,
    address: "Neue Kampstrasse 2, 23714 Bad Malente-Gremsmuehlen, Germany",
    ops_phone: "04523 407-0",
    ops_email: "info@curtius-klinik.de",
    website: "https://www.curtius-klinik.de",
    comments: "Specialties: Psychotherapy.",
  },
  {
    id: "germany-23730-neustadt-in-holstein-kinderzentrum-pelzerhaken",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Kinderzentrum Pelzerhaken",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Neustadt in Holstein",
    region: "Schleswig-Holstein",
    lat: 54.088556,
    lon: 10.8630891,
    address: "Zum Leuchtturm 4, 23730 Neustadt in Holstein, Germany",
    ops_phone: "04561 7109-0",
    ops_email: "verwaltung@kinderzentrum-pelzerhaken.de",
    website: "https://www.kinderzentrum-pelzerhaken.de",
    comments: "Specialties: Neurology.",
  },
  {
    id: "germany-23730-neustadt-in-holstein-schoen-klinik-neustadt",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Schoen Klinik Neustadt",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Neustadt in Holstein",
    region: "Schleswig-Holstein",
    lat: 54.0903295,
    lon: 10.8292319,
    address: "Am Kiebitzberg 10, 23730 Neustadt in Holstein, Germany",
    ops_phone: "04561 54-0",
    ops_email: "KlinikumNeustadt@schoen-kliniken.de",
    website: "https://www.schoen-klinik.de/neustadt",
    comments: "Specialties: Surgery; Internal medicine; Neurology; Urology.",
  },
  {
    id: "germany-27498-helgoland-paracelsus-nordseeklinik-helgoland",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Paracelsus Nordseeklinik Helgoland",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Helgoland",
    region: "Germany",
    lat: 54.17867,
    lon: 7.8865194,
    address: "Invasorenpfad, 27498 Helgoland, Germany",
    ops_phone: "04725 803-0",
    ops_email: "helgoland@pk-mx.de",
    website: "https://www.paracelsus-kliniken.de/akut/helgoland",
    comments: "Specialties: Internal medicine; Neurology.",
  },
  {
    id: "germany-24306-ploen-fachklinik-freudenholm-ruhleben",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Fachklinik Freudenholm-Ruhleben",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Ploen",
    region: "Germany",
    lat: 54.1372198,
    lon: 10.4457014,
    address: "Missionsweg 3, 24306 Ploen, Germany",
    ops_phone: "04522 789-0",
    ops_email: "info@fachklinik-freudenholm-ruhleben.de",
    website: "https://www.fachklinik-freudenholm-ruhleben.de",
    comments: "Specialties: Psychiatry; Addiction psychiatry.",
  },
  {
    id: "germany-24211-preetz-klinik-preetz-kreiskrankenhaus-des-kreises-ploen",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinik Preetz Kreiskrankenhaus des Kreises Ploen",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Preetz",
    region: "Germany",
    lat: 54.2389471,
    lon: 10.2781206,
    address: "Am Krankenhaus 5, 24211 Preetz, Germany",
    ops_phone: "04342 801-0",
    ops_email: "info@klinik-preetz.de",
    website: "https://klinik-preetz.de/",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Internal medicine; Urology.",
  },
  {
    id: "germany-24340-eckernfoerde-schoen-klinik-eckernfoerde",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Schoen Klinik Eckernfoerde",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Eckernfoerde",
    region: "Germany",
    lat: 54.4830887,
    lon: 9.8164902,
    address: "Schleswiger Str. 114 - 116, 24340 Eckernfoerde, Germany",
    ops_phone: "04351 882-0",
    website: "https://www.schoen-klinik.de/eckernfoerde",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Gynecology; Obstetrics; Internal medicine; Urology; Day clinic: internal medicine; Day clinic: psychiatry.",
  },
  {
    id: "germany-24119-kronshagen-praxisklinik-kronshagen",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Praxisklinik Kronshagen",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kronshagen",
    region: "Germany",
    lat: 54.3375314,
    lon: 10.0980154,
    address: "Eichkoppelweg 74, 24119 Kronshagen, Germany",
    ops_phone: "0431 5456-677",
    ops_email: "verwaltung@pkkh.de",
    website: "https://www.praxisklinik-kronshagen.de",
    comments: "Specialties: Surgery; Vascular surgery; Orthopedics.",
  },
  {
    id: "germany-24768-rendsburg-schoen-klinik-rendsburg",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Schoen Klinik Rendsburg",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Rendsburg",
    region: "Germany",
    lat: 54.2972385,
    lon: 9.6578833,
    address: "Lilienstr. 20 - 28, 24768 Rendsburg, Germany",
    ops_phone: "04331 200-0",
    ops_email: "info@imland.de",
    website: "https://www.schoen-klinik.de/rendsburg",
    comments: "Specialties: Ophthalmology; Surgery; Vascular surgery; Gynecology and obstetrics; Gynecology; Obstetrics; ENT; Internal medicine; Geriatrics; Pediatrics; Oral and maxillofacial surgery; Neurology.",
  },
  {
    id: "germany-24376-kappeln-margarethen-klinik-kappeln",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Margarethen-Klinik Kappeln",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kappeln",
    region: "Germany",
    lat: 54.6583625,
    lon: 9.9240358,
    address: "Konsul-Lorentzen-Str. 3, 24376 Kappeln, Germany",
    ops_phone: "04642 52-0",
    website: "https://margarethenklinik.de/",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Internal medicine; Urology.",
  },
  {
    id: "germany-24837-schleswig-helios-klinik-schleswig",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Helios Klinik Schleswig",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Schleswig",
    region: "Germany",
    lat: 54.5250902,
    lon: 9.5658283,
    address: "St. Juergener Str. 1-3, 24837 Schleswig, Germany",
    ops_phone: "04621 812-0",
    website: "https://www.helios-kliniken.de/klinik/schleswig.html",
    comments: "Specialties: Surgery; Trauma/accident surgery; Gynecology and obstetrics; ENT; Internal medicine; Pediatrics; Oral and maxillofacial surgery; Neurology; Urology; Other specialties; Day clinic: internal medicine.",
  },
  {
    id: "germany-24576-bad-bramstedt-klinikum-bad-bramstedt-gmbh",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinikum Bad Bramstedt GmbH",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Bad Bramstedt",
    region: "Germany",
    lat: 53.9038149,
    lon: 9.893233,
    address: "Oskar-Alexander-Strasse 26, 24576 Bad Bramstedt, Germany",
    ops_phone: "04192 90-0",
    ops_email: "info@klinikumbadbramstedt.de",
    website: "https://www.klinikumbadbramstedt.de",
    comments: "Specialties: Internal medicine; Rheumatology; Geriatrics; Orthopedics; Orthopedic rheumatology.",
  },
  {
    id: "germany-24576-bad-bramstedt-schoen-klinik-bad-bramstedt",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Schoen Klinik Bad Bramstedt",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Bad Bramstedt",
    region: "Germany",
    lat: 53.9045657,
    lon: 9.8881911,
    address: "Birkenweg 10, 24576 Bad Bramstedt, Germany",
    ops_phone: "04192 504-0",
    ops_email: "info@schoen-kliniken.de",
    website: "https://www.schoen-klinik.de/",
    comments: "Specialties: Psychotherapy.",
  },
  {
    id: "germany-23795-bad-segeberg-ak-segeberger-kliniken",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "AK Segeberger Kliniken",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Bad Segeberg",
    region: "Germany",
    lat: 53.9412295,
    lon: 10.3090167,
    address: "Krankenhausstr. 2, 23795 Bad Segeberg, Germany",
    ops_phone: "04551 801-0",
    ops_email: "info@segebergerkliniken.de",
    website: "https://www.segebergerkliniken.de",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Cardiac surgery; Internal medicine; Cardiology; Neurology; Psychotherapy; Urology; Day clinic: psychotherapy.",
  },
  {
    id: "germany-24558-henstedt-ulzburg-paracelsus-klinik-henstedt-ulzburg-gmbh",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Paracelsus Klinik Henstedt-Ulzburg GmbH",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Henstedt-Ulzburg",
    region: "Germany",
    lat: 53.7488769,
    lon: 10.0071822,
    address: "Wilstedter Str. 134, 24558 Henstedt-Ulzburg, Germany",
    ops_phone: "04191 961-801",
    ops_email: "info@paracelsus-kliniken.de",
    website: "https://www.paracelsus-kliniken.de",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Gynecology; Obstetrics; Internal medicine; Pediatrics; Neonatology; Urology.",
  },
  {
    id: "germany-25524-itzehoe-klinikum-und-seniorenzentrum-itzehoe",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinikum und Seniorenzentrum Itzehoe",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Itzehoe",
    region: "Germany",
    lat: 53.9417141,
    lon: 9.5030113,
    address: "Robert-Koch-Str. 2, 25524 Itzehoe, Germany",
    ops_phone: "04821 772-0",
    ops_email: "info@kh-itzehoe.de",
    website: "https://www.kh-itzehoe.de",
    comments: "Specialties: Surgery; Trauma/accident surgery; Gynecology and obstetrics; ENT; Internal medicine; Geriatrics; Pediatrics; Neurology; Psychiatry; Psychotherapy; Urology; Other specialties.",
  },
  {
    id: "germany-23863-bargfeld-stegen-heinrich-sengelmann-krankenhaus",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Heinrich-Sengelmann-Krankenhaus",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Bargfeld-Stegen",
    region: "Germany",
    lat: 53.7572899,
    lon: 10.1537822,
    address: "Kayhuder Str. 65, 23863 Bargfeld-Stegen, Germany",
    ops_phone: "04535 505-0",
    ops_email: "hsk@alsterdorf.de",
    website: "https://www.heinrich-sengelmann-krankenhaus.de",
    comments: "Specialties: Psychiatry; Psychotherapy.",
  },
  {
    id: "germany-22927-grosshansdorf-lungenclinic-grosshansdorf",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "LungenClinic Grosshansdorf",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Grosshansdorf",
    region: "Germany",
    lat: 53.6603964,
    lon: 10.280777,
    address: "Woehrendamm 80, 22927 Grosshansdorf, Germany",
    ops_phone: "04102 601-0",
    ops_email: "info@lungenclinic.de",
    website: "https://www.lungenclinic.de/",
    comments: "Specialties: Surgery; Thoracic surgery; Internal medicine; Pulmonology.",
  },
  {
    id: "germany-22927-grosshansdorf-park-klinik-manhagen-orthopaedische-fachklinik",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Park-Klinik Manhagen Orthopaedische Fachklinik",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Grosshansdorf",
    region: "Germany",
    lat: 53.6630889,
    lon: 10.2571761,
    address: "Sieker Landstr. 19, 22927 Grosshansdorf, Germany",
    ops_phone: "04102 605-0",
    ops_email: "info@manhagen.de",
    website: "https://www.manhagen.de/",
    comments: "Specialties: Ophthalmology; Orthopedics.",
  },
  {
    id: "germany-21465-reinbek-krankenhaus-reinbek-st-adolf-stift",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Krankenhaus Reinbek St. Adolf-Stift",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Reinbek",
    region: "Germany",
    lat: 53.509736,
    lon: 10.2406578,
    address: "Hamburger Str. 41, 21465 Reinbek, Germany",
    ops_phone: "040 7280-0",
    ops_email: "info@krankenhaus-reinbek.de",
    website: "https://www.krankenhaus-reinbek.de",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Internal medicine; Urology.",
  },
  {
    id: "germany-20099-hamburg-asklepios-klinik-st-georg",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Asklepios Klinik St. Georg",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.5598876,
    lon: 10.0176941,
    address: "Lohmuehlenstr. 5, 20099 Hamburg, Germany",
    ops_phone: "040 181884-2306",
    ops_email: "info.stgeorg@asklepios.com",
    website: "https://www.asklepios.com/sankt-georg",
    comments: "Specialties: Surgery; Vascular surgery; Trauma/accident surgery; ENT; Dermatology and venereology; Cardiac surgery; Internal medicine; Angiology; Gastroenterology; Hematology/oncology; Cardiology; Neurosurgery.",
  },
  {
    id: "germany-22763-hamburg-akk-altonaer-kinderkrankenhaus-ggmbh",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "AKK Altonaer Kinderkrankenhaus gGmbH",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.552139,
    lon: 9.9130502,
    address: "Bleickenallee 38, 22763 Hamburg, Germany",
    ops_phone: "040 88908-0",
    ops_email: "info@kinderkrankenhaus.net",
    website: "https://www.kinderkrankenhaus.net",
    comments: "Specialties: Pediatric surgery; Pediatrics; Child and adolescent psychiatry; Orthopedics; Day clinic: other specialties.",
  },
  {
    id: "germany-22763-hamburg-asklepios-klinik-altona",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Asklepios Klinik Altona",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.5549245,
    lon: 9.9023394,
    address: "Paul-Ehrlich-Str.1, 22763 Hamburg, Germany",
    ops_phone: "040 181884-2306",
    ops_email: "info.altona@asklepios.com",
    website: "https://www.asklepios.com/altona",
    comments: "Specialties: Ophthalmology; Surgery; Vascular surgery; Trauma/accident surgery; Visceral surgery; Gynecology and obstetrics; ENT; Internal medicine; Gastroenterology; Hematology/oncology; Cardiology; Rheumatology.",
  },
  {
    id: "germany-22609-hamburg-klinikgruppe-dr-guth",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinikgruppe Dr.Guth",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.5565862,
    lon: 9.8538596,
    address: "Juergensallee 46-48, 22609 Hamburg, Germany",
    ops_phone: "040 82281-0",
    ops_email: "zentralverwaltung@drguth.de",
    website: "https://www.drguth.de",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Internal medicine.",
  },
  {
    id: "germany-22587-hamburg-krankenhaus-tabea-im-artemed-klinikverbund",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Krankenhaus Tabea im Artemed-Klinikverbund",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.5641314,
    lon: 9.7916409,
    address: "Koesterbergstrasse 32, 22587 Hamburg, Germany",
    ops_phone: "040 86692-0",
    ops_email: "info@Tabea-Krankenhaus.de",
    website: "https://www.tabea-fachklinik.de/",
    comments: "Specialties: Surgery; Orthopedics.",
  },
  {
    id: "germany-22559-hamburg-asklepios-westklinikum-hamburg",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Asklepios Westklinikum Hamburg",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.5822769,
    lon: 9.7775459,
    address: "Suurheid 20, 22559 Hamburg, Germany",
    ops_phone: "040 8191-0",
    ops_email: "westklinikum.hh.rissen@asklepios.com",
    website: "https://www.asklepios.com/hamburg/westklinikum/",
    comments: "Specialties: Surgery; Internal medicine; Geriatrics; Psychiatry; Psychotherapy; Urology; Day clinic: psychiatry; Day clinic: psychotherapy.",
  },
  {
    id: "germany-20259-hamburg-agaplesion-diakonieklinikum-hamburg",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Agaplesion Diakonieklinikum Hamburg",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.5717926,
    lon: 9.965901,
    address: "Hohe Weide 17, 20259 Hamburg, Germany",
    ops_phone: "040 79020-0",
    ops_email: "info@d-k-h.de",
    website: "https://www.d-k-h.de/start",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Gynecology; Obstetrics; Internal medicine; Geriatrics; Day clinic: geriatrics.",
  },
  {
    id: "germany-22767-hamburg-helios-endo-klinik-hamburg",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "HELIOS Endo-Klinik Hamburg",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.5508292,
    lon: 9.9542356,
    address: "Holstenstrasse 2, 22767 Hamburg, Germany",
    ops_phone: "040 3197-0",
    ops_email: "info@endo.de",
    website: "https://www.endo-klinik.de",
    comments: "Specialties: Surgery; Neurosurgery.",
  },
  {
    id: "germany-20148-hamburg-praxisklinik-am-rothenbaum-gmbh",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Praxisklinik am Rothenbaum GmbH",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.5669031,
    lon: 9.993073,
    address: "HeimhuderStr. 38, 20148 Hamburg, Germany",
    ops_phone: "040 413314-0",
    ops_email: "info@klinikrothenbaum.de",
    website: "https://klinikrothenbaum.jimdoweb.com/",
    comments: "Specialties: Surgery; Vascular surgery; ENT; Orthopedics; Plastic surgery; Other specialties.",
  },
  {
    id: "germany-20251-hamburg-facharztklinik-hamburg-betriebsteil-michaelis-betriebsteil-andreasbrunnen",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Facharztklinik Hamburg Betriebsteil \"Michaelis\" Betriebsteil \"Andreasbrunnen\"",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.5883283,
    lon: 9.9727691,
    address: "Martinistrasse 78, 20251 Hamburg, Germany",
    ops_phone: "040 49065-0",
    ops_email: "info@facharztklinik-hamburg.de",
    website: "https://www.facharztklinik-hamburg.de",
    comments: "Specialties: Ophthalmology; Surgery; Gynecology and obstetrics; Gynecology; ENT; Orthopedics; Urology.",
  },
  {
    id: "germany-20251-hamburg-university-medical-center-hamburg-eppendorf-uke",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "University Medical Center Hamburg-Eppendorf (UKE)",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.5909051,
    lon: 9.9753758,
    address: "Martinistrasse 52, 20251 Hamburg, Germany",
    ops_phone: "040 7410-0",
    ops_email: "info@uke.de",
    website: "https://www.uke.de",
    comments: "Specialties: Ophthalmology; Surgery; Trauma/accident surgery; Gynecology and obstetrics; Gynecology; Obstetrics; ENT; Dermatology and venereology; Internal medicine; Hematology/oncology; Nephrology; Pediatrics.",
  },
  {
    id: "germany-22337-hamburg-evangelisches-krankenhaus-alsterdorf",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Evangelisches Krankenhaus Alsterdorf",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.6141622,
    lon: 10.0243857,
    address: "Elisabeth-Fluegge-Strasse 1, 22337 Hamburg, Germany",
    ops_phone: "040 5077-3202",
    ops_email: "eka@alsterdorf.de",
    website: "https://evangelisches-krankenhaus-alsterdorf.de/",
    comments: "Specialties: Surgery; Internal medicine; Geriatrics; Child and adolescent psychiatry; Neurology; Psychiatry; Day clinic: geriatrics; Day clinic: child and adolescent psychiatry; Day clinic: psychiatry.",
  },
  {
    id: "germany-22087-hamburg-marienkrankenhaus-hamburg",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Marienkrankenhaus Hamburg",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.559033,
    lon: 10.0307399,
    address: "Alfredstrasse 9, 22087 Hamburg, Germany",
    ops_phone: "040 2546-0",
    ops_email: "info@marienkrankenhaus.org",
    website: "https://www.marienkrankenhaus.org",
    comments: "Specialties: Surgery; Trauma/accident surgery; Gynecology and obstetrics; ENT; Internal medicine; Geriatrics; Neurology; Urology.",
  },
  {
    id: "germany-22081-hamburg-schoen-klinik-hamburg-eilbek",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Schoen Klinik Hamburg Eilbek",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.577895,
    lon: 10.0529663,
    address: "Dehnhaide 120, 22081 Hamburg, Germany",
    ops_phone: "040 181884-2306",
    website: "https://www.schoen-klinik.de/hamburg-eilbek",
    comments: "Specialties: Surgery; Internal medicine; Geriatrics; Neurology; Psychiatry; Psychotherapy; Other specialties; Day clinic: geriatrics; Day clinic: psychiatry; Day clinic: psychotherapy.",
  },
  {
    id: "germany-22307-hamburg-asklepios-klinik-barmbek",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Asklepios Klinik Barmbek",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.6064338,
    lon: 10.0364354,
    address: "Ruebenkamp 220, 22307 Hamburg, Germany",
    ops_phone: "040 181884-2306",
    ops_email: "info.barmbek@asklepios.com",
    website: "https://www.asklepios.com/barmbek",
    comments: "Specialties: Ophthalmology; Surgery; Trauma/accident surgery; Visceral surgery; Gynecology and obstetrics; Gynecology; Obstetrics; Internal medicine; Gastroenterology; Hematology/oncology; Cardiology; Nephrology.",
  },
  {
    id: "germany-22419-hamburg-asklepios-klinik-nord-ochsenzoll-heidberg",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Asklepios Klinik Nord - Ochsenzoll/Heidberg",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.674239,
    lon: 10.0075204,
    address: "Langenhorner Chaussee 560, 22419 Hamburg, Germany",
    ops_phone: "040 181884-2306",
    ops_email: "info.nord@asklepios.com",
    website: "https://www.asklepios.com/klinikumnord/",
    comments: "Specialties: Ophthalmology; Surgery; Gynecology and obstetrics; ENT; Internal medicine; Geriatrics; Pediatrics; Neonatology; Oral and maxillofacial surgery; Neurosurgery; Neurology; Psychiatry.",
  },
  {
    id: "germany-22049-hamburg-bundeswehrkrankenhaus-hamburg",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Bundeswehrkrankenhaus Hamburg",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.5952689,
    lon: 10.0782912,
    address: "Lesserstrasse 180, 22049 Hamburg, Germany",
    ops_phone: "040 6947-0",
    ops_email: "BwKrhsHamburg@bundeswehr.org",
    website: "https://www.bundeswehrkrankenhaus.de",
    comments: "Specialties: Surgery; Trauma/accident surgery; ENT; Dermatology and venereology; Internal medicine; Oral and maxillofacial surgery; Neurosurgery; Neurology; Urology.",
  },
  {
    id: "germany-22043-hamburg-asklepios-klinik-wandsbek",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Asklepios Klinik Wandsbek",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.5699008,
    lon: 10.0880663,
    address: "Alphonsstrasse 14, 22043 Hamburg, Germany",
    ops_phone: "040 181884-2306",
    ops_email: "info.wandsbek@asklepios.com",
    website: "https://www.asklepios.com/wandsbek",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Internal medicine; Geriatrics; Neurology; Day clinic: geriatrics.",
  },
  {
    id: "germany-22359-hamburg-amalie-sieveking-hospital-hamburg",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Amalie Sieveking Hospital Hamburg",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.6411202,
    lon: 10.1518478,
    address: "Haselkamp 33, 22359 Hamburg, Germany",
    ops_phone: "040 64411-0",
    ops_email: "info@amalie.de",
    website: "https://amalie.de/",
    comments: "Specialties: Surgery; Vascular surgery; Trauma/accident surgery; Gynecology and obstetrics; Gynecology; Obstetrics; Internal medicine; Cardiology; Geriatrics; Day clinic: geriatrics.",
  },
  {
    id: "germany-22149-hamburg-wilhelmstift-catholic-children-s-hospital",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Wilhelmstift Catholic Children's Hospital",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.5873149,
    lon: 10.1649951,
    address: "Liliencronstrasse 130, 22149 Hamburg, Germany",
    ops_phone: "040 67377-0",
    ops_email: "info@kkh-wilhelmstift.de",
    website: "https://www.kkh-wilhelmstift.de",
    comments: "Specialties: Pediatric surgery; Pediatrics; Neonatology; Child and adolescent psychiatry; Day clinic: child and adolescent psychiatry; Day clinic: other specialties.",
  },
  {
    id: "germany-21029-hamburg-bethesda-krankenhaus-bergedorf-ggmbh",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Bethesda Krankenhaus Bergedorf gGmbH",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.4857786,
    lon: 10.2360022,
    address: "Glindersweg 80, 21029 Hamburg, Germany",
    ops_phone: "040 72554-0",
    ops_email: "info@bkb.info",
    website: "https://www.klinik-bergedorf.de/start",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Internal medicine; Geriatrics; Neurology; Psychiatry; Day clinic: geriatrics; Day clinic: psychiatry.",
  },
  {
    id: "germany-21075-hamburg-asklepios-klinik-harburg",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Asklepios Klinik Harburg",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.4594942,
    lon: 9.9485623,
    address: "Eissendorfer Pferdeweg 52, 21075 Hamburg, Germany",
    ops_phone: "040 181884-2306",
    ops_email: "info.harburg@asklepios.com",
    website: "https://www.asklepios.com/harburg",
    comments: "Specialties: Surgery; Vascular surgery; Thoracic surgery; Trauma/accident surgery; Visceral surgery; Gynecology and obstetrics; Gynecology; ENT; Cardiac surgery; Internal medicine; Gastroenterology; Cardiology.",
  },
  {
    id: "germany-21075-hamburg-helios-mariahilf-clinic-hamburg",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Helios Mariahilf Clinic Hamburg",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Hamburg",
    region: "Germany",
    lat: 53.4698687,
    lon: 9.9378098,
    address: "Stader Strasse 203c, 21075 Hamburg, Germany",
    ops_phone: "040 79006-0",
    ops_email: "info.mariahilf@helios-kliniken.de",
    website: "https://www.helios-kliniken.de/hamburg",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Internal medicine; Pediatric surgery; Pediatrics.",
  },
  {
    id: "germany-38102-braunschweig-ev-luth-diakonissenanstalt-marienstift",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Ev.-luth. Diakonissenanstalt Marienstift",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Braunschweig",
    region: "Germany",
    lat: 52.2586577,
    lon: 10.5457979,
    address: "Helmstedter Strasse 35, 38102 Braunschweig, Germany",
    ops_phone: "0531 7011-0",
    ops_email: "marienstift@marienstift-braunschweig.de",
    website: "https://www.krankenhaus-marienstift.de/",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Gynecology; Obstetrics; ENT; Internal medicine.",
  },
  {
    id: "germany-38124-braunschweig-herzogin-elisabeth-hospital",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Herzogin-Elisabeth-Hospital",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Braunschweig",
    region: "Germany",
    lat: 52.2329718,
    lon: 10.5262744,
    address: "Leipziger Strasse 24, 38124 Braunschweig, Germany",
    ops_phone: "0531 699-0",
    ops_email: "info@heh-bs.de",
    website: "https://www.heh-bs.de",
    comments: "Specialties: Surgery; Internal medicine; Orthopedics.",
  },
  {
    id: "germany-38124-braunschweig-klinik-am-zuckerberg-gmbh",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinik am Zuckerberg GmbH",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Braunschweig",
    region: "Germany",
    lat: 52.241816,
    lon: 10.52942,
    address: "Zuckerbergweg 2, 38124 Braunschweig, Germany",
    ops_phone: "0531 2633-0",
    ops_email: "info@klinikamzuckerberg.de",
    website: "https://www.klinikamzuckerberg.de",
    comments: "Specialties: Surgery.",
  },
  {
    id: "germany-38226-salzgitter-helios-klinikum-salzgitter",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Helios Klinikum Salzgitter",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Salzgitter",
    region: "Germany",
    lat: 52.1541708,
    lon: 10.3183178,
    address: "Kattowitzer Strasse 191, 38226 Salzgitter, Germany",
    ops_phone: "05341 835-0",
    ops_email: "info.salzgitter@helios-gesundheit.de",
    website: "https://www.helios-gesundheit.de",
    comments: "Specialties: Surgery; Gynecology and obstetrics; ENT; Internal medicine; Pediatrics; Urology.",
  },
  {
    id: "germany-38259-salzgitter-st-elisabeth-hospital-salzgitter",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "St. Elisabeth Hospital Salzgitter",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Salzgitter",
    region: "Germany",
    lat: 52.0454249,
    lon: 10.3718545,
    address: "Liebenhaller Strasse 20, 38259 Salzgitter, Germany",
    ops_phone: "05341 8240",
    ops_email: "kontakt@st-elisabeth-sz.de",
    website: "https://st-elisabeth-sz.de/",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Internal medicine.",
  },
  {
    id: "germany-38440-wolfsburg-klinikum-wolfsburg",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinikum Wolfsburg",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Wolfsburg",
    region: "Germany",
    lat: 52.4136733,
    lon: 10.7685967,
    address: "Sauerbruchstrasse 7, 38440 Wolfsburg, Germany",
    ops_phone: "05361 80-0",
    ops_email: "info@klinikum.wolfsburg.de",
    website: "https://www.klinikum-wolfsburg.de",
    comments: "Specialties: Ophthalmology; Surgery; Trauma/accident surgery; Gynecology and obstetrics; Gynecology; Obstetrics; ENT; Internal medicine; Pediatrics; Neurology; Radiotherapy; Urology.",
  },
  {
    id: "germany-38518-gifhorn-helios-klinikum-gifhorn",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Helios Klinikum Gifhorn",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Gifhorn",
    region: "Germany",
    lat: 52.4971131,
    lon: 10.5482638,
    address: "Campus 6, 38518 Gifhorn, Germany",
    ops_phone: "05371 87-0",
    ops_email: "sekretariat.gf@helios-gesundheit.de",
    website: "https://www.helios-gesundheit.de",
    comments: "Specialties: Surgery; Trauma/accident surgery; Visceral surgery; Gynecology and obstetrics; Gynecology; Obstetrics; ENT; Internal medicine; Gastroenterology; Cardiology; Pulmonology; Geriatrics.",
  },
  {
    id: "germany-29378-wittingen-helios-klinik-wittingen",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Helios Klinik Wittingen",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Wittingen",
    region: "Germany",
    lat: 52.7301646,
    lon: 10.7402495,
    address: "Gustav-Dobberkau-Strasse 5, 29378 Wittingen, Germany",
    ops_phone: "05831 22-0",
    ops_email: "info.wittingen@helios-gesundheit.de",
    website: "https://www.helios-gesundheit.de",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Internal medicine.",
  },
  {
    id: "germany-38667-bad-harzburg-asklepios-harzklinik-bad-harzburg",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Asklepios Harzklinik Bad Harzburg",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Bad Harzburg",
    region: "Germany",
    lat: 51.8857325,
    lon: 10.5759978,
    address: "Ilsenburger Strasse 95, 38667 Bad Harzburg, Germany",
    ops_phone: "05322 76-0",
    ops_email: "badharzburg@asklepios.com",
    website: "https://www.asklepios.com/konzern",
    comments: "Specialties: Internal medicine; Orthopedics.",
  },
  {
    id: "germany-38704-liebenburg-privat-nervenklinik-dr-med-fontheim",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Privat-Nervenklinik Dr. med. Fontheim",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Liebenburg",
    region: "Germany",
    lat: 52.022791,
    lon: 10.4317625,
    address: "Lindenstrasse 15, 38704 Liebenburg, Germany",
    ops_phone: "05346 81-0",
    ops_email: "info@klinik-dr-fontheim.de",
    website: "https://www.fontheim.de/home",
    comments: "Specialties: Psychiatry; Addiction psychiatry; Psychotherapy; Day clinic: psychiatry.",
  },
  {
    id: "germany-38723-seesen-asklepios-kliniken-schildautal-seesen",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Asklepios Kliniken Schildautal Seesen",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Seesen",
    region: "Germany",
    lat: 51.8830284,
    lon: 10.216045,
    address: "Karl-Herold-Strasse 1, 38723 Seesen, Germany",
    ops_phone: "05381 74-0",
    ops_email: "seesen@asklepios.com",
    website: "https://www.asklepios.com/konzern",
    comments: "Specialties: Surgery; Vascular surgery; Internal medicine; Neurosurgery; Neurology.",
  },
  {
    id: "germany-38642-goslar-asklepios-harzklinik-goslar",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Asklepios Harzklinik Goslar",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Goslar",
    region: "Germany",
    lat: 51.928178,
    lon: 10.4425161,
    address: "Koesliner Strasse 12, 38642 Goslar, Germany",
    ops_phone: "05321 44-0",
    ops_email: "goslar@asklepios.com",
    website: "https://www.asklepios.com/konzern",
    comments: "Specialties: Surgery; Trauma/accident surgery; Gynecology and obstetrics; Gynecology; Obstetrics; ENT; Internal medicine; Oral and maxillofacial surgery; Urology.",
  },
  {
    id: "germany-38678-clausthal-zellerfeld-asklepios-harzklinik-clausthal-zellerfeld",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Asklepios Harzklinik Clausthal-Zellerfeld",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Clausthal-Zellerfeld",
    region: "Germany",
    lat: 51.8075417,
    lon: 10.3340287,
    address: "Windmuehlenstrasse 1, 38678 Clausthal-Zellerfeld, Germany",
    ops_phone: "05323 714-0",
    ops_email: "clausthal-zellerfeld@asklepios.com",
    website: "https://www.asklepios.com/konzern",
    comments: "Specialties: Surgery; Internal medicine.",
  },
  {
    id: "germany-38350-helmstedt-helios-st-marienberg-clinic-helmstedt",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Helios St. Marienberg Clinic Helmstedt",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Helmstedt",
    region: "Germany",
    lat: 52.2318762,
    lon: 10.9993091,
    address: "Conringstrasse 26, 38350 Helmstedt, Germany",
    ops_phone: "05351 14-0",
    ops_email: "info.helmstedt@helios-gesundheit.de",
    website: "https://www.helios-gesundheit.de/helmstedt",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Gynecology; Obstetrics; Internal medicine; Urology.",
  },
  {
    id: "germany-38154-koenigslutter-awo-psychiatriezentrum",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "AWO Psychiatriezentrum",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Koenigslutter",
    region: "Germany",
    lat: 52.2437748,
    lon: 10.8126117,
    address: "Vor dem Kaiserdom 10, 38154 Koenigslutter, Germany",
    ops_phone: "05353 90-0",
    ops_email: "poststelle@awo-apz.de",
    website: "https://www.awo-psychiatriezentrum.de",
    comments: "Specialties: Child and adolescent psychiatry; Psychiatry; Addiction psychiatry; Psychotherapy; Day clinic: child and adolescent psychiatry; Day clinic: psychiatry.",
  },
  {
    id: "germany-37154-northeim-helios-albert-schweitzer-clinic-northeim",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Helios Albert-Schweitzer Clinic Northeim",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Northeim",
    region: "Germany",
    lat: 51.7298077,
    lon: 9.9788643,
    address: "Albert-Schweitzer-Weg 1, 37154 Northeim, Germany",
    ops_phone: "05551 97-0",
    ops_email: "information.northeim@helios-gesundheit.de",
    website: "https://www.helios-gesundheit.de/northeim",
    comments: "Specialties: Ophthalmology; Surgery; Vascular surgery; Trauma/accident surgery; Visceral surgery; Gynecology and obstetrics; Gynecology; Obstetrics; ENT; Internal medicine; Angiology; Gastroenterology.",
  },
];
