const germanyHospitalClinicProviders = [
  {
    id: "germany-24939-flensburg-malteser-foerdeklinikum-st-katharina-waldstrasse",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Malteser Foerdeklinikum St. Katharina - Waldstrasse site",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Flensburg",
    region: "Schleswig-Holstein",
    lat: 54.7922897,
    lon: 9.4207165,
    address: "Waldstrasse 17, 24939 Flensburg, Germany",
    ops_phone: "0461 816-0",
    ops_email: "krankenhaus.flensburg@malteser.org",
    website: "https://www.malteser-foerdeklinikum.de/",
    comments: "Beds listed: 317. Specialties: Surgery; ENT; Internal medicine; Geriatrics; Oral and maxillofacial surgery; Day clinic: geriatrics.",
  },
  {
    id: "germany-24113-kiel-helios-klinikum-kiel",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Helios Klinikum Kiel",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3045385,
    lon: 10.1168612,
    address: "Hamburger Chaussee 77, 24113 Kiel, Germany",
    ops_phone: "0431 7206-300",
    website: "https://www.helios-kliniken.de/klinik/kiel",
    comments: "Beds listed: 50. Specialties: Surgery; ENT; Oral and maxillofacial surgery; Neurosurgery; Orthopedics; Urology.",
  },
  {
    id: "germany-24116-kiel-klinik-flechsig",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinik Flechsig",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3228203,
    lon: 10.1163371,
    address: "Chemnitzstrasse 33, 24116 Kiel, Germany",
    ops_phone: "0431 3397100",
    ops_email: "info@kliniik-flechsig.de",
    website: "https://www.klinik-flechsig.de",
    comments: "Beds listed: 30. Specialties: ENT.",
  },
  {
    id: "germany-24106-kiel-lubinus-clinicum",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Lubinus Clinicum",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3529232,
    lon: 10.1167164,
    address: "Steenbeker Weg 25, 24106 Kiel, Germany",
    ops_phone: "0431 388-0",
    ops_email: "info@mvz-lubinus.de",
    website: "https://www.lubinus-kliniken.de/",
    comments: "Beds listed: 199. Specialties: Surgery; Orthopedics.",
  },
  {
    id: "germany-24105-kiel-nordblick-augenklinik-bellevue",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "nordBLICK Augenklinik Bellevue",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3456265,
    lon: 10.1492353,
    address: "Lindenallee 21-23, 24105 Kiel, Germany",
    ops_phone: "0431 30108-0",
    ops_email: "uthoff@augenklinik-bellevue.de",
    website: "https://www.augenklinik-bellevue.de",
    comments: "Beds listed: 18. Specialties: Ophthalmology.",
  },
  {
    id: "germany-24116-kiel-park-klinik",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Park-Klinik Kiel",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3266908,
    lon: 10.1257264,
    address: "Goethestrasse 11, 24116 Kiel, Germany",
    ops_phone: "0431 5909-0",
    ops_email: "carecenter@park-klinik-kiel.de",
    website: "https://www.park-klinik-kiel.de",
    comments: "Beds listed: 46. Specialties: Surgery; Gynecology and obstetrics; ENT; Internal medicine.",
  },
  {
    id: "germany-24114-kiel-kieler-fenster-psychiatric-day-clinic",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Kieler Fenster Psychiatric Day Clinic",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3085101,
    lon: 10.1263,
    address: "Alte Luebecker Chaussee 1, 24114 Kiel, Germany",
    ops_phone: "0431 649802-0",
    ops_email: "tagesklinik@kieler-fenster.de",
    website: "https://www.kieler-fenster.de",
    comments: "Specialties: Day clinic: psychiatry.",
  },
  {
    id: "germany-24149-kiel-schmerzklinik-kiel",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Schmerzklinik Kiel",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3288942,
    lon: 10.1838107,
    address: "Heikendorfer Weg 9-27, 24149 Kiel, Germany",
    ops_phone: "0431 20099-0",
    ops_email: "Kiel@Schmerzklinik.de",
    website: "https://schmerzklinik.de/",
    comments: "Beds listed: 80. Specialties: Neurology.",
  },
  {
    id: "germany-24116-kiel-staedtisches-krankenhaus-kiel",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Staedtisches Krankenhaus Kiel",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3228203,
    lon: 10.1163371,
    address: "Chemnitzstrasse 33, 24116 Kiel, Germany",
    ops_phone: "0431 1697-0",
    ops_email: "info@krankenhaus-kiel.de",
    website: "https://www.krankenhaus-kiel.de",
    comments: "Beds listed: 678. Specialties: Surgery; Gynecology and obstetrics; Internal medicine; Geriatrics; Pediatrics; Urology; Other specialties; Day clinic: geriatrics.",
  },
  {
    id: "germany-24105-kiel-university-medical-center-schleswig-holstein-kiel",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "University Medical Center Schleswig-Holstein - Kiel Campus",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3278096,
    lon: 10.1417471,
    address: "Brunswiker Strasse 10, 24105 Kiel, Germany",
    ops_phone: "0431 597-0",
    ops_email: "info@uksh.de",
    website: "https://www.uksh.de",
    comments: "Beds listed: 1107. Specialties: Ophthalmology; Surgery; Trauma/accident surgery; Gynecology and obstetrics; Gynecology; Obstetrics; ENT; Dermatology and venereology; Cardiac surgery; Internal medicine; Hematology/oncology; Cardiology.",
  },
  {
    id: "germany-23566-luebeck-red-cross-hospital-geriatrics-centre",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Red Cross Hospital Luebeck - Geriatrics Centre",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Luebeck",
    region: "Schleswig-Holstein",
    lat: 53.8730757,
    lon: 10.7085117,
    address: "Marlistrasse 10, 23566 Luebeck, Germany",
    ops_phone: "0451 6202-0",
    ops_email: "info.TZ@drk-schwhl.de",
    website: "https://www.drk-schwesternschaft-luebeck.de/",
    comments: "Beds listed: 164. Specialties: Geriatrics; Day clinic: geriatrics.",
  },
  {
    id: "germany-23538-luebeck-university-medical-center-schleswig-holstein-luebeck",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "University Medical Center Schleswig-Holstein - Luebeck Campus",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Luebeck",
    region: "Schleswig-Holstein",
    lat: 53.8358374,
    lon: 10.7087465,
    address: "Ratzeburger Allee 160, 23538 Luebeck, Germany",
    ops_phone: "0451 500-0",
    ops_email: "info@uk-sh.de",
    website: "https://www.uksh.de",
    comments: "Beds listed: 1049. Specialties: Ophthalmology; Surgery; Trauma/accident surgery; Gynecology and obstetrics; Gynecology; Obstetrics; ENT; Dermatology and venereology; Cardiac surgery; Internal medicine; Cardiology; Pulmonology.",
  },
  {
    id: "germany-23560-luebeck-sana-kliniken-luebeck-south-hospital",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Sana Kliniken Luebeck - South Hospital",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Luebeck",
    region: "Schleswig-Holstein",
    lat: 53.8488707,
    lon: 10.6879537,
    address: "Kronsforder Allee 71/73, 23560 Luebeck, Germany",
    ops_phone: "0451 585-01",
    ops_email: "info@sana-luebeck.de",
    website: "https://www.sana-luebeck.de",
    comments: "Specialties: Surgery; Internal medicine; Hematology/oncology; Neurology; Urology; Other specialties.",
  },
  {
    id: "germany-25541-brunsbuettel-westkuestenklinikum-brunsbuettel",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Westkuestenklinikum Brunsbuettel",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Brunsbuettel",
    region: "Schleswig-Holstein",
    lat: 53.8999702,
    lon: 9.1462558,
    address: "Delbrueckstr. 2, 25541 Brunsbuettel, Germany",
    ops_phone: "04852 980-0",
    website: "https://www.westkuestenklinikum.de/",
    comments: "Specialties: Surgery; Internal medicine; Geriatrics; Urology; Day clinic: internal medicine; Day clinic: geriatrics; Day clinic: psychiatry.",
  },
  {
    id: "germany-25746-heide-westkuestenklinikum-heide",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Westkuestenklinikum Heide",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Heide",
    region: "Schleswig-Holstein",
    lat: 54.1991651,
    lon: 9.0810799,
    address: "Esmarchstr. 50, 25746 Heide, Germany",
    ops_phone: "0481 785-0",
    ops_email: "info@wkk-hei.de",
    website: "https://www.westkuestenklinikum.de/",
    comments: "Specialties: Surgery; Vascular surgery; Trauma/accident surgery; Gynecology and obstetrics; ENT; Internal medicine; Geriatrics; Pediatrics; Neurosurgery; Neurology; Nuclear medicine; Psychiatry.",
  },
  {
    id: "germany-21502-geesthacht-krankenhaus-geesthacht-vitalcampus-geesthacht",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Krankenhaus Geesthacht / Vitalcampus Geesthacht",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Geesthacht",
    region: "Schleswig-Holstein",
    lat: 53.4315254,
    lon: 10.3858089,
    address: "Am Runden Berge 3, 21502 Geesthacht, Germany",
    ops_phone: "04152 179-0",
    ops_email: "info@johanniter-krankenhaus.de",
    website: "https://www.johanniter.de/johanniter-kliniken/krankenhaus-geesthacht/",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Internal medicine; Psychiatry; Psychotherapy; Day clinic: psychiatry; Day clinic: psychotherapy.",
  },
  {
    id: "germany-23909-ratzeburg-drk-hospital-moelln-ratzeburg",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "DRK Hospital Moelln-Ratzeburg",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Ratzeburg",
    region: "Schleswig-Holstein",
    lat: 53.6898388,
    lon: 10.778847,
    address: "Roepersberg 2, 23909 Ratzeburg, Germany",
    ops_phone: "04541 884-01",
    ops_email: "info@drk-krankenhaus.de",
    website: "https://www.drk-krankenhaus.de",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Gynecology; Obstetrics; Internal medicine; Urology.",
  },
  {
    id: "germany-23909-ratzeburg-ratzeburg-geriatric-clinic",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Ratzeburg Geriatric Clinic",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Ratzeburg",
    region: "Schleswig-Holstein",
    lat: 53.6825424,
    lon: 10.7681319,
    address: "Roepersberg 47, 23909 Ratzeburg, Germany",
    ops_phone: "04541 13-3700",
    ops_email: "info@geriatrie-ratzeburg.de",
    website: "https://www.geriatrie-ratzeburg.de",
    comments: "Specialties: Geriatrics; Day clinic: geriatrics.",
  },
  {
    id: "germany-25813-husum-klinik-dr-winkler-amedes-clinic-husum",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinik Dr. Winkler - Amedes Clinic Husum",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Husum",
    region: "Schleswig-Holstein",
    lat: 54.4800559,
    lon: 9.0558461,
    address: "Brinckmannstr. 6, 25813 Husum, Germany",
    ops_phone: "04841 6911-0",
    ops_email: "klinik-winkler@foni.de",
    website: "https://www.amedes-klinik-husum.de/",
    comments: "Specialties: Surgery.",
  },
  {
    id: "germany-25813-husum-klinikum-nordfriesland-husum-hospital",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinikum Nordfriesland - Husum Hospital",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Husum",
    region: "Schleswig-Holstein",
    lat: 54.4833008,
    lon: 9.0502002,
    address: "Erichsenweg 16, 25813 Husum, Germany",
    ops_phone: "04841 660-0",
    ops_email: "husum@klinikum-nf.de",
    website: "https://www.klinikum-nf.de",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Gynecology; Obstetrics; Internal medicine; Geriatrics; Urology; Day clinic: geriatrics.",
  },
  {
    id: "germany-25899-niebuell-klinikum-nordfriesland-niebuell-hospital",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinikum Nordfriesland - Niebuell Hospital",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Niebuell",
    region: "Schleswig-Holstein",
    lat: 54.7930609,
    lon: 8.8436755,
    address: "Gather Landstr. 75, 25899 Niebuell, Germany",
    ops_phone: "04661 151",
    website: "https://www.klinikum-nf.de",
    comments: "Specialties: Surgery; ENT; Internal medicine; Geriatrics; Day clinic: internal medicine; Day clinic: geriatrics.",
  },
  {
    id: "germany-25938-wyk-auf-foehr-klinikum-nordfriesland-foehr-amrum-island-clinic",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinikum Nordfriesland - Foehr-Amrum Island Clinic",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Wyk auf Foehr",
    region: "Schleswig-Holstein",
    lat: 54.6853714,
    lon: 8.5642967,
    address: "Rebbelstieg 24, 25938 Wyk auf Foehr, Germany",
    ops_phone: "04681 48-0",
    ops_email: "wyk@klinikum-nf.de",
    website: "https://www.klinikum-nf.de",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Internal medicine.",
  },
  {
    id: "germany-25980-westerland-asklepios-nordseeklinik-westerland",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Asklepios Nordseeklinik Westerland",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Westerland",
    region: "Schleswig-Holstein",
    lat: 54.9254688,
    lon: 8.3132852,
    address: "Norderstrasse 81, 25980 Westerland, Germany",
    ops_phone: "04651 84-1201",
    ops_email: "sylt@asklepios.de",
    website: "https://www.asklepios.com/sylt",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Dermatology and venereology; Internal medicine; Urology.",
  },
  {
    id: "germany-23611-bad-schwartau-helios-agnes-karll-hospital-bad-schwartau",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Helios Agnes Karll Hospital Bad Schwartau",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Bad Schwartau",
    region: "Schleswig-Holstein",
    lat: 53.9224163,
    lon: 10.6938415,
    address: "Am Hochkamp 21, 23611 Bad Schwartau, Germany",
    ops_phone: "0451 2007-0",
    ops_email: "postmaster@badschwartau.helios-kliniken.de",
    website: "https://www.helios-kliniken.de/badschwartau",
    comments: "Specialties: Surgery; Gynecology and obstetrics; Gynecology; ENT; Internal medicine; Oral and maxillofacial surgery; Neurosurgery; Orthopedics; Urology.",
  },
  {
    id: "germany-23701-eutin-sankt-elisabeth-hospital-eutin",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Sankt Elisabeth Hospital Eutin",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Eutin",
    region: "Schleswig-Holstein",
    lat: 54.1384268,
    lon: 10.6106838,
    address: "Ploener Str. 42, 23701 Eutin, Germany",
    ops_phone: "04521 802-0",
    ops_email: "info@sek-eutin.de",
    website: "https://sek-eutin.de/",
    comments: "Specialties: Internal medicine; Geriatrics; Other specialties; Day clinic: geriatrics.",
  },
  {
    id: "germany-23714-bad-malente-gremsmuehlen-august-bier-clinic-neurology-and-neurorehabilitation",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "August-Bier Clinic - Neurology and Neurorehabilitation",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Bad Malente-Gremsmuehlen",
    region: "Schleswig-Holstein",
    lat: 54.1643762,
    lon: 10.5477242,
    address: "Diekseepromenade 7-11, 23714 Bad Malente-Gremsmuehlen, Germany",
    ops_phone: "04523 405-0",
    ops_email: "info@august-bier-klinik.de",
    website: "https://www.august-bier-klinik.de",
    comments: "Specialties: Neurology.",
  },
  {
    id: "germany-23714-bad-malente-gremsmuehlen-curtius-clinic-psychosomatic-medicine-and-psychotherapy",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Curtius Clinic - Psychosomatic Medicine and Psychotherapy",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Bad Malente-Gremsmuehlen",
    region: "Schleswig-Holstein",
    lat: 54.1718808,
    lon: 10.5661185,
    address: "Neue Kampstrasse 2, 23714 Bad Malente-Gremsmuehlen, Germany",
    ops_phone: "04523 407-0",
    ops_email: "info@curtius-klinik.de",
    website: "https://www.curtius-klinik.de",
    comments: "Specialties: Psychotherapy.",
  },
  {
    id: "germany-23730-neustadt-in-holstein-kinderzentrum-pelzerhaken",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Kinderzentrum Pelzerhaken",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Neustadt in Holstein",
    region: "Schleswig-Holstein",
    lat: 54.088556,
    lon: 10.8630891,
    address: "Zum Leuchtturm 4, 23730 Neustadt in Holstein, Germany",
    ops_phone: "04561 7109-0",
    ops_email: "verwaltung@kinderzentrum-pelzerhaken.de",
    website: "https://www.kinderzentrum-pelzerhaken.de",
    comments: "Specialties: Neurology.",
  },
  {
    id: "germany-23730-neustadt-in-holstein-schoen-klinik-neustadt",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Schoen Klinik Neustadt",
    type: "Hospital/Clinic",
    agreement: "Agreement pending",
    main_country: "Germany",
    country: "Germany",
    city: "Neustadt in Holstein",
    region: "Schleswig-Holstein",
    lat: 54.0903295,
    lon: 10.8292319,
    address: "Am Kiebitzberg 10, 23730 Neustadt in Holstein, Germany",
    ops_phone: "04561 54-0",
    ops_email: "KlinikumNeustadt@schoen-kliniken.de",
    website: "https://www.schoen-klinik.de/neustadt",
    comments: "Specialties: Surgery; Internal medicine; Neurology; Urology.",
  },
];
