const germanyHospitalClinicProviders = [
  {
    id: "germany-24939-flensburg-malteser-foerdeklinikum-st-katharina-waldstrasse",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Malteser Foerdeklinikum St. Katharina - Waldstrasse site",
    type: "Hospital/Clinic",
    agreement: "Agreement signed",
    main_country: "Germany",
    country: "Germany",
    city: "Flensburg",
    region: "Schleswig-Holstein",
    lat: 54.7922897,
    lon: 9.4207165,
    address: "Waldstrasse 17, 24939 Flensburg, Germany",
    ops_phone: "0461 816-0",
    ops_email: "krankenhaus.flensburg@malteser.org",
    website: "https://www.malteser-foerdeklinikum.de/",
    comments: "Beds listed: 317. Specialties: Surgery; ENT; Internal medicine; Geriatrics; Oral and maxillofacial surgery; Day clinic: geriatrics.",
  },
  {
    id: "germany-24113-kiel-helios-klinikum-kiel",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Helios Klinikum Kiel",
    type: "Hospital/Clinic",
    agreement: "Agreement signed",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3045385,
    lon: 10.1168612,
    address: "Hamburger Chaussee 77, 24113 Kiel, Germany",
    ops_phone: "0431 7206-300",
    website: "https://www.helios-kliniken.de/klinik/kiel",
    comments: "Beds listed: 50. Specialties: Surgery; ENT; Oral and maxillofacial surgery; Neurosurgery; Orthopedics; Urology.",
  },
  {
    id: "germany-24116-kiel-klinik-flechsig",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Klinik Flechsig",
    type: "Hospital/Clinic",
    agreement: "Agreement signed",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3228203,
    lon: 10.1163371,
    address: "Chemnitzstrasse 33, 24116 Kiel, Germany",
    ops_phone: "0431 3397100",
    ops_email: "info@kliniik-flechsig.de",
    website: "https://www.klinik-flechsig.de",
    comments: "Beds listed: 30. Specialties: ENT.",
  },
  {
    id: "germany-24106-kiel-lubinus-clinicum",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Lubinus Clinicum",
    type: "Hospital/Clinic",
    agreement: "Agreement signed",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3529232,
    lon: 10.1167164,
    address: "Steenbeker Weg 25, 24106 Kiel, Germany",
    ops_phone: "0431 388-0",
    ops_email: "info@mvz-lubinus.de",
    website: "https://www.lubinus-kliniken.de/",
    comments: "Beds listed: 199. Specialties: Surgery; Orthopedics.",
  },
  {
    id: "germany-24105-kiel-nordblick-augenklinik-bellevue",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "nordBLICK Augenklinik Bellevue",
    type: "Hospital/Clinic",
    agreement: "Agreement signed",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3456265,
    lon: 10.1492353,
    address: "Lindenallee 21-23, 24105 Kiel, Germany",
    ops_phone: "0431 30108-0",
    ops_email: "uthoff@augenklinik-bellevue.de",
    website: "https://www.augenklinik-bellevue.de",
    comments: "Beds listed: 18. Specialties: Ophthalmology.",
  },
  {
    id: "germany-24116-kiel-park-klinik",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Park-Klinik Kiel",
    type: "Hospital/Clinic",
    agreement: "Agreement signed",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3266908,
    lon: 10.1257264,
    address: "Goethestrasse 11, 24116 Kiel, Germany",
    ops_phone: "0431 5909-0",
    ops_email: "carecenter@park-klinik-kiel.de",
    website: "https://www.park-klinik-kiel.de",
    comments: "Beds listed: 46. Specialties: Surgery; Gynecology and obstetrics; ENT; Internal medicine.",
  },
  {
    id: "germany-24114-kiel-kieler-fenster-psychiatric-day-clinic",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Kieler Fenster Psychiatric Day Clinic",
    type: "Hospital/Clinic",
    agreement: "Agreement signed",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3085101,
    lon: 10.1263,
    address: "Alte Luebecker Chaussee 1, 24114 Kiel, Germany",
    ops_phone: "0431 649802-0",
    ops_email: "tagesklinik@kieler-fenster.de",
    website: "https://www.kieler-fenster.de",
    comments: "Specialties: Day clinic: psychiatry.",
  },
  {
    id: "germany-24149-kiel-schmerzklinik-kiel",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Schmerzklinik Kiel",
    type: "Hospital/Clinic",
    agreement: "Agreement signed",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3288942,
    lon: 10.1838107,
    address: "Heikendorfer Weg 9-27, 24149 Kiel, Germany",
    ops_phone: "0431 20099-0",
    ops_email: "Kiel@Schmerzklinik.de",
    website: "https://schmerzklinik.de/",
    comments: "Beds listed: 80. Specialties: Neurology.",
  },
  {
    id: "germany-24116-kiel-staedtisches-krankenhaus-kiel",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Staedtisches Krankenhaus Kiel",
    type: "Hospital/Clinic",
    agreement: "Agreement signed",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3228203,
    lon: 10.1163371,
    address: "Chemnitzstrasse 33, 24116 Kiel, Germany",
    ops_phone: "0431 1697-0",
    ops_email: "info@krankenhaus-kiel.de",
    website: "https://www.krankenhaus-kiel.de",
    comments: "Beds listed: 678. Specialties: Surgery; Gynecology and obstetrics; Internal medicine; Geriatrics; Pediatrics; Urology; Other specialties; Day clinic: geriatrics.",
  },
  {
    id: "germany-24105-kiel-university-medical-center-schleswig-holstein-kiel",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "University Medical Center Schleswig-Holstein - Kiel Campus",
    type: "Hospital/Clinic",
    agreement: "Agreement signed",
    main_country: "Germany",
    country: "Germany",
    city: "Kiel",
    region: "Schleswig-Holstein",
    lat: 54.3278096,
    lon: 10.1417471,
    address: "Brunswiker Strasse 10, 24105 Kiel, Germany",
    ops_phone: "0431 597-0",
    ops_email: "info@uksh.de",
    website: "https://www.uksh.de",
    comments: "Beds listed: 1107. Specialties: Ophthalmology; Surgery; Trauma/accident surgery; Gynecology and obstetrics; Gynecology; Obstetrics; ENT; Dermatology and venereology; Cardiac surgery; Internal medicine; Hematology/oncology; Cardiology.",
  },
  {
    id: "germany-23566-luebeck-red-cross-hospital-geriatrics-centre",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "Red Cross Hospital Luebeck - Geriatrics Centre",
    type: "Hospital/Clinic",
    agreement: "Agreement signed",
    main_country: "Germany",
    country: "Germany",
    city: "Luebeck",
    region: "Schleswig-Holstein",
    lat: 53.8730757,
    lon: 10.7085117,
    address: "Marlistrasse 10, 23566 Luebeck, Germany",
    ops_phone: "0451 6202-0",
    ops_email: "info.TZ@drk-schwhl.de",
    website: "https://www.drk-schwesternschaft-luebeck.de/",
    comments: "Beds listed: 164. Specialties: Geriatrics; Day clinic: geriatrics.",
  },
  {
    id: "germany-23538-luebeck-university-medical-center-schleswig-holstein-luebeck",
    source: "germany-hospital-clinic-import-2026-06-19",
    name: "University Medical Center Schleswig-Holstein - Luebeck Campus",
    type: "Hospital/Clinic",
    agreement: "Agreement signed",
    main_country: "Germany",
    country: "Germany",
    city: "Luebeck",
    region: "Schleswig-Holstein",
    lat: 53.8358374,
    lon: 10.7087465,
    address: "Ratzeburger Allee 160, 23538 Luebeck, Germany",
    ops_phone: "0451 500-0",
    ops_email: "info@uk-sh.de",
    website: "https://www.uksh.de",
    comments: "Beds listed: 1049. Specialties: Ophthalmology; Surgery; Trauma/accident surgery; Gynecology and obstetrics; Gynecology; Obstetrics; ENT; Dermatology and venereology; Cardiac surgery; Internal medicine; Cardiology; Pulmonology.",
  },
];
