// Provider additions confirmed by the network team on 2026-08-06.
const networkUpdateProviders = [
  {
    id: "network-update-tanzania-arusha-medivac-house-calls-20260806",
    source: "network-team-update-2026-08-06",
    name: "ARUSHA MEDIVAC - House Visits",
    type: "House Calls",
    agreement: "Agreement signed",
    main_country: "Tanzania",
    country: "Tanzania",
    city: "Arusha",
    region: "Arusha",
    lat: -3.3668439,
    lon: 36.6257181,
    address: "Arusha Airport, Arusha, Tanzania",
    network_manager: "Joleen D'Mello",
    ops_phone: "+255 767 996 996; +255 683 996 996",
    ops_email: "info@arushamedivac.org; joleen@arushamedivac.org",
    website: "https://arushamedivac.org/",
    comments: "House visits are available within the city of Arusha only.",
  },
  {
    id: "network-update-spain-barcelona-barnaclinic-20260806",
    source: "network-team-update-2026-08-06",
    name: "Barnaclínic+",
    type: "Hospital/Clinic",
    agreement: "Agreement signed",
    main_country: "Spain",
    country: "Spain",
    city: "Barcelona",
    region: "Catalonia",
    lat: 41.3891274,
    lon: 2.1517594,
    address: "Carrer de Villarroel, 170, 08036 Barcelona, Spain",
    network_manager: "Marta Fernandez, Head of International Area and Projects",
    ops_phone: "+34 93 227 93 91 ext. 389151; +34 650 040 613",
    ops_email: "barnaclinic_int@barnaclinic.cat",
    website: "https://www.barnaclinic.com/en/",
    comments: "Private care service within Hospital Clínic Barcelona facilities.",
  },
];
