// Provider additions confirmed by the network team.
const networkUpdateProviders = [
  {
    id: "network-update-china-sanya-health-management-20260810",
    source: "network-team-update-2026-08-10",
    name: "SANYA HEALTH MANAGEMENT",
    type: "TPA",
    agreement: "Agreement signed",
    main_country: "China",
    country: "China",
    city: "Sanya",
    region: "Hainan",
    lat: 18.2528,
    lon: 109.5119,
    address: "3rd Floor, Zhi Li Hotel, 11 Xianghe Road, Jiyang District, Sanya, Hainan 572000, China",
    network_manager: "Jalushia Ma",
    manager_email: "network@sanyahealthmanagement.com",
    ops_phone: "+86 156 0806 3958",
    ops_email: "operations@sanyahealthmanagement.com",
    website: "https://sanyahealthmanagement.com/",
    comments: "Mutual service agreement. The provider may also request assistance for cases in Europe.",
  },
  {
    id: "network-update-tanzania-arusha-medivac-house-calls-20260806",
    source: "network-team-update-2026-08-06",
    name: "ARUSHA MEDIVAC - House Visits",
    type: "House Calls",
    agreement: "Agreement signed",
    main_country: "Tanzania",
    country: "Tanzania",
    city: "Arusha",
    region: "Arusha",
    lat: -3.3668439,
    lon: 36.6257181,
    address: "Arusha Airport, Arusha, Tanzania",
    network_manager: "Joleen D'Mello",
    ops_phone: "+255 767 996 996; +255 683 996 996",
    ops_email: "info@arushamedivac.org; joleen@arushamedivac.org",
    website: "https://arushamedivac.org/",
    comments: "House visits are available within the city of Arusha only.",
  },
  {
    id: "network-update-spain-barcelona-barnaclinic-20260806",
    source: "network-team-update-2026-08-06",
    name: "Barnaclínic+",
    type: "Hospital/Clinic",
    agreement: "Agreement signed",
    main_country: "Spain",
    country: "Spain",
    city: "Barcelona",
    region: "Catalonia",
    lat: 41.3891274,
    lon: 2.1517594,
    address: "Carrer de Villarroel, 170, 08036 Barcelona, Spain",
    network_manager: "Marta Fernandez, Head of International Area and Projects",
    ops_phone: "+34 93 227 93 91 ext. 389151; +34 650 040 613",
    ops_email: "barnaclinic_int@barnaclinic.cat",
    website: "https://www.barnaclinic.com/en/",
    comments: "Private care service within Hospital Clínic Barcelona facilities.",
  },
];
